
Below are relevant files from an R package related to my repbox project

# Package regtranslate


# FILE: /home/rstudio/repbox/regtranslate/DESCRIPTION
```
Package: regtranslate
Type: Package
Title: Translate regression commands using information from repdb 
Version: 0.1
Author: Sebastian Kranz (Ulm University)
Maintainer: Sebastian Kranz <sebastian.kranz@uni-ulm.de>
Description: Currently only contains Stata to R translation
License: Not yet licensed. Not yet in public domain
Depends: dplyr, restorepoint, stringtools, fixest, broom, stringi
Encoding: UTF-8
LazyData: true
```
# END OF FILE: /home/rstudio/repbox/regtranslate/DESCRIPTION

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/cterms_r.R
```
replace_cterm_special_symbols = function(cterms) {
  cterms = gsub("@",".__.", cterms, fixed=TRUE)
  cterms = gsub("#","._..", cterms, fixed=TRUE)
  cterms = gsub("=",".._.", cterms, fixed=TRUE)
  cterms
}

unreplace_cterm_special_symbols = function(cterms) {
  cterms = gsub(".__.","@", cterms, fixed=TRUE)
  cterms = gsub("._..","#", cterms, fixed=TRUE)
  cterms = gsub(".._.","=", cterms, fixed=TRUE)
  cterms
}


replace_cterms_dot = function(cterms) {
  cterms = as.character(cterms)

  if (length(cterms)==0) {
    return(cterms)
  }

  # 1. Expand compact chained TS prefixes, e.g.
  # LD.x1 -> L.D.x1
  # L2D3S4.x1 -> L2.D3.S4.x1
  repeat {
    new_cterms = gsub(
      "(^|#|@|\\.)([LlFfDdSsOo][0-9]*)([LlFfDdSsOo][0-9]*)(?=[@\\.])",
      "\\1\\2.\\3",
      cterms,
      perl = TRUE
    )
    if (identical(new_cterms, cterms)) {
      break
    }
    cterms = new_cterms
  }

  # 2. Canonicalize TS operators to upper case and drop explicit 1
  # d.  -> D.
  # d@  -> D@
  # l1. -> L.
  # l1@ -> L@
  ops = c("l", "f", "d", "s", "o")
  for (op in ops) {
    OP = toupper(op)

    cterms = gsub(
      paste0("(^|#|@|\\.)([", op, OP, "])1(?=[@\\.])"),
      paste0("\\1", OP),
      cterms,
      perl = TRUE
    )

    cterms = gsub(
      paste0("(^|#|@|\\.)([", op, OP, "])([0-9]+)(?=[@\\.])"),
      paste0("\\1", OP, "\\3"),
      cterms,
      perl = TRUE
    )

    cterms = gsub(
      paste0("(^|#|@|\\.)([", op, OP, "])(?=[@\\.])"),
      paste0("\\1", OP),
      cterms,
      perl = TRUE
    )
  }

  # 3. Convert only dots that separate actual TS prefixes from the next token.
  # Do not touch decimal points in factor levels such as x1=-1.874.
  repeat {
    new_cterms = gsub(
      "(^|#|@)([LFDSO][0-9]*)\\.",
      "\\1\\2@",
      cterms,
      perl = TRUE
    )
    if (identical(new_cterms, cterms)) {
      break
    }
    cterms = new_cterms
  }

  cterms
}

# We might put these functions back to repboxReg
cterm_of_r_coefs = function(terms, regvar, rcmd=NULL, dot_to_at=from_stata, from_stata=TRUE) {
  restore.point("cterm_of_r_coefs")

  #rcmd = rep(rcmd, length.out = length(terms))

  #cterms = terms

  # Currently we can use the fixest version for all regressions
  # but that might change
  cterms = cterm_of_r_coefs_fixest(terms, regvar, dot_to_at=dot_to_at)

  cterms
}

cterm_of_r_coefs_fixest = function(terms, regvar, dot_to_at=FALSE) {
  restore.point("r_coefs_cterm_fixest")

  terms = gsub("`","", terms, fixed=TRUE)
  terms = gsub("::","=", terms, fixed=TRUE)

  factor.rx = "factor\\(([a-zA-Z0-9_.]*)\\)"
  terms = gsub(factor.rx,"\\1=",terms,fixed=FALSE)

  if (dot_to_at) {
    terms = replace_cterms_dot(terms)
  }

  rows = which(startsWith(terms,"fit_"))
  if (length(rows)>0) {
    terms.no.fit = substring(terms[rows], 5)
    change = (!terms[rows] %in% regvar$ia_cterm) & (terms.no.fit %in% regvar$ia_cterm)
    terms[rows[change]] = terms.no.fit[change]
  }

  ia_rows = which(has.substr(terms, "#"))
  if (length(ia_rows) > 0) {
    terms[ia_rows] = split_and_sort(terms[ia_rows], split = "#")
  }

  terms
}

# cterm_of_r_coefs_fixest = function(terms, regvar, dot_to_at=FALSE) {
#   restore.point("r_coefs_cterm_fixest")
#
#   terms = gsub("`","", terms, fixed=TRUE)
#   # factor in form: farmass_q::2
#   # to farmass_q=2
#   terms = gsub("::","=", terms, fixed=TRUE)
#   #terms = gsub(" ","", terms, fixed=TRUE)
#
#   # factor in form
#   # factor(i1)4:factor(d1)1
#   # to i1=4:d1=1
#   factor.rx = "factor\\(([a-zA-Z0-9_.]*)\\)"
#   terms = gsub(factor.rx,"\\1=",terms,fixed=FALSE)
#
#   # Replace . by @ if . was a Stata prefix
#   if (dot_to_at) {
#     terms = gsub(".","@", terms, fixed=TRUE)
#   }
#
#   # In an IV regression feols adds "fit_" to the result
#   # variable. We want to remove that
#   rows = which(startsWith(terms,"fit_"))
#   if (length(rows)>0) {
#     terms.no.fit = substring(terms[rows], 5)
#     change = (!terms[rows] %in% regvar$ia_cterm) & (terms.no.fit %in% regvar$ia_cterm)
#     terms[rows[change]] = terms.no.fit[change]
#   }
#
#   terms
# }
cterm_to_saveterm = function(cterms) {
  # We use the safe replacements from replace_cterm_special_symbols
  # instead of raw . and .. to avoid colliding with variables that naturally contain dots
  replace_cterm_special_symbols(cterms)
}

saveterm_to_cterm = function(saveterms) {
  unreplace_cterm_special_symbols(saveterms)
}

cterm_to_saveterm_cols = function(dat) {
  colnames(dat) = cterm_to_saveterm(colnames(dat))
  dat
}

saveterm_to_cterm_cols = function(dat) {
  colnames(dat) = saveterm_to_cterm(colnames(dat))
  dat
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/cterms_r.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/drop_like_stata.R
```
#' Drop perfect predictors for binary outcome models
#'
#' Emulates Stata's behavior of dropping variables and observations
#' that perfectly predict the outcome in logit/probit models.
#'
#' @param dat data.frame
#' @param depvar character, name of dependent variable
#' @param indepvars character vector of independent variables
#' @param verbose logical, if TRUE prints Stata-like notes
#' @return A list with `dat` (filtered data) and `indepvars` (variables kept).
#' @export
stata_drop_perfect_predictors = function(dat, depvar, indepvars, verbose = TRUE) {
  if (length(depvar) != 1 || !depvar %in% colnames(dat)) return(list(dat=dat, indepvars=indepvars))

  y = dat[[depvar]]
  if (is.logical(y)) y = as.integer(y)
  y = as.numeric(y)
  # Stata treats exactly 0 as failure, and non-zero as success
  y = ifelse(y == 0, 0, 1)

  uni_y = unique(na.omit(y))
  if (length(uni_y) < 2) {
    return(list(dat=dat, indepvars=indepvars))
  }

  kept_vars = indepvars
  keep_rows = !is.na(y)

  changed = TRUE

  while(changed) {
    changed = FALSE
    cur_y = y[keep_rows]

    for (var in kept_vars) {
      if (!var %in% colnames(dat)) next
      x = dat[[var]]

      if (is.character(x) || is.factor(x)) next

      cur_x = x[keep_rows]
      if (all(is.na(cur_x))) next

      # CRITICAL FIX: Stata only applies the "!= 0" heuristic to dummy variables.
      # If we don't check this, continuous variables with a single 0 observation
      # will falsely appear as perfect predictors and drop the observation.
      uni_x = unique(na.omit(cur_x))
      if (length(uni_x) > 2) next

      idx_neq_0 = which(!is.na(cur_x) & cur_x != 0)
      idx_eq_0 = which(!is.na(cur_x) & cur_x == 0)

      if (length(idx_neq_0) > 0 && length(idx_eq_0) > 0) {

        y_neq = cur_y[idx_neq_0]
        if (min(y_neq) == max(y_neq)) {
          if (verbose) {
             cat(sprintf("note: %s != 0 predicts %s perfectly;\n      %s omitted and %d obs not used.\n",
                         var, ifelse(y_neq[1]==1, "success", "failure"), var, length(idx_neq_0)))
          }
          keep_rows[which(keep_rows)[idx_neq_0]] = FALSE
          kept_vars = setdiff(kept_vars, var)
          changed = TRUE
          break
        }

        y_eq = cur_y[idx_eq_0]
        if (min(y_eq) == max(y_eq)) {
          if (verbose) {
             cat(sprintf("note: %s == 0 predicts %s perfectly;\n      %s omitted and %d obs not used.\n",
                         var, ifelse(y_eq[1]==1, "success", "failure"), var, length(idx_eq_0)))
          }
          keep_rows[which(keep_rows)[idx_eq_0]] = FALSE
          kept_vars = setdiff(kept_vars, var)
          changed = TRUE
          break
        }
      }
    }
  }

  if (!all(keep_rows)) {
    dat = dat[keep_rows, , drop=FALSE]
  }

  list(dat = dat, indepvars = kept_vars)
}



#' Emulate Stata's listwise deletion (e(sample))
#'
#' Drops NA, but also empty strings ("") and non-finite numbers (Inf, NaN),
#' which Stata treats as missing values during marksample.
#' @export
stata_drop_missing = function(dat, vars) {
  vars = intersect(vars, colnames(dat))
  if (length(vars) == 0) return(dat)

  keep = rep(TRUE, nrow(dat))
  for (v in vars) {
    val = dat[[v]]
    if (is.character(val) || is.factor(val)) {
      char_val = as.character(val)
      keep = keep & !is.na(char_val) & (char_val != "")
    } else if (is.numeric(val)) {
      keep = keep & is.finite(val)
    } else {
      keep = keep & !is.na(val)
    }
  }

  if (!all(keep)) {
    dat = dat[keep, , drop = FALSE]
  }
  dat
}

```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/drop_like_stata.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/investigate.R
```
# Helper functions for investigation

example = function() {
  library(repboxReg)
  project.dir = "~/repbox/projects_reg/aejapp_3_2_2/"

  core = readRDS("~/repbox/projects_reg/aejapp_3_2_2/metareg/s2r/regdb/s2r_core.Rds")
  details = readRDS("~/repbox/projects_reg/aejapp_3_2_2/metareg/s2r/regdb/s2r_details.Rds")

  s2r_reprex(project.dir, step=52)
}

#' Generates a folder with a reproducible example that shall help
#' detect why an R translation yields different results than the Stata version.
s2r_reprex = function(project.dir, step, out.dir = file.path(project.dir,"metareg","s2r","reprex", step), details = load_parcel(project.dir,"s2r","s2r_details"), dap=get.project.dap(project.dir, make.if.missing=FALSE)) {
  restore.point("s2r_reprex")

  dat_file = repboxReg::mr_get_cache_file(project.dir, step)

  s2r_regdb_dir = file.path(project.dir,"metareg","s2r","regdb")

  core = readRDS(file.path(s2r_regdb_dir,"s2r_core.Rds"))
  details = readRDS(file.path(s2r_regdb_dir,"s2r_details.Rds"))

  rreg = details$reg[details$reg$step==step,]

  r_code = rreg$cmdline
}



# Put the following functions back to repboxReg

stata_code_reg_data_preparation = function(project.dir, step, dap=get.project.dap(project.dir, make.if.missing=FALSE)) {
  restore.point("stata_code_step_data_preparation")
  astep = step
  txt = "\n\nset more off\n"
  path = dap$path.df[dap$path.df$astep == astep,]
  # 1. Get data file
  step = path$step[1]
  file = mr_get_cache_file(mr$project.dir, step)
  txt = paste0(txt,'\nuse "', file,'", clear\n')

  # 2. code for all other stepsdata modification steps
  steps = path$step[-1]
  txt = paste0(txt,"\n", paste0(mr$step.df$stata_code[steps], collapse = "\n"))

}

r_code_reg_data_preparation = function(project.dir, step, dap=get.project.dap(project.dir, make.if.missing=FALSE)) {
  restore.point("stata_code_step_data_preparation")
  astep = step
  txt = "\n\nset more off\n"
  path = dap$path.df[dap$path.df$astep == astep,]
  # 1. Get data file
  step = path$step[1]
  file = mr_get_cache_file(mr$project.dir, step)
  txt = paste0(txt,'\nuse "', file,'", clear\n')

  # 2. code for all other stepsdata modification steps
  steps = path$step[-1]
  txt = paste0(txt,"\n", paste0(mr$step.df$stata_code[steps], collapse = "\n"))

}



mr_write_path_stata_code = function(mr, astep=first(mr$path.df$astep), code.file=paste0(mr$project.dir,"/metareg/step_",astep,".do"), add.line.info = !is.null(run.df), run.df=mr$run.df,...) {
  restore.point("mr_write_path_stata_code")

  txt = "\n\nset more off\n"
  path = dap$path.df[dap$path.df$astep == astep,]
  # 1. Get data file
  step = path$step[1]
  file = mr_get_cache_file(mr$project.dir, step)
  txt = paste0(txt,'\nuse "', file,'", clear\n')

  # 2. code for all other stepsdata modification steps
  steps = path$step[-1]
  txt = paste0(txt,"\n", paste0(mr$step.df$stata_code[steps], collapse = "\n"))

  writeLines(txt, code.file)
  invisible(txt)
}


load_parcel = function(project.dir, metaid, parcel) {
  parcel.file=file.path(project.dir,metaid,"regdb", paste0(parcel,".Rds"))
  if (!file.exists(parcel.file)) return(NULL)
  readRDS(parcel.file)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/investigate.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/mr_s2r.R
```
s2r_example = function() {
  library(regtranslate)
  library(repboxReg)
  #project.dir = file.path("C:/libraries/repbox/projects_reg",project)

  project = "testsupp"

  project.dir = file.path("~/repbox/projects_reg/",project)

  mr = mr_s2r_study(project.dir)

  parcels = mr$saved_parcels

  rstudioapi::filesPaneNavigate(paste0(project.dir))

  dat = readRDS("C:/libraries/repbox/projects_reg/testsupp/metareg/s2r/s2r_agg.Rds")$regcoef
}


mr_s2r_study = function(project.dir, variant = "s2r") {
  library(repboxReg)
  restore.point("mr_s2r_study")
  project = basename(project.dir)

  opts = mr_opts(stop.on.error = TRUE,create.regxvar.cols = TRUE)

  mr = mr_init_study(project.dir,metaid="s2r",step_run_fun = s2r_step_run_fun, study_agg_fun = s2r_study_agg_fun, opts = opts, version = 0)
  mr$variant = variant

  # If there is no used regression
  # just save the default stuff for an empty study and return
  if (mr_uses_no_reg(mr)) {
    return(mr_finish(mr))
  }

  # Load tables from regdb beyond "reg" that will be used
  mr = mr_load_parcels(mr, c("reg_core", "cmdpart","regcoef","regvar","regxvar"))

  # Run the study
  mr = mr_run(mr)

  mr_finish(mr)
}


# In R we will perform a regression using fixest (lm might take too long)
s2r_step_run_fun =  function(mr, step, reg, dat, org.dat, infeasible_filter, ...) {
  restore.point("s2r_step_run_fun")

  regxvar = mr_get_base_table(mr, "regxvar", steps=step)
  regvar = mr_get_base_table(mr, "regvar", steps=step)
  cmdpart = mr_get_base_table(mr, "cmdpart", steps=step)

  # All columns relevant for the regression
  reg$infeasible_filter = infeasible_filter

  #if (step==4) stop()
  code_df = reg_stata_to_r_code(reg, regvar, regxvar, cmdpart)

  code_df = code_df %>% add_reg_function_code(add_restore_point = TRUE)

  code = paste0(code_df$code, collapse="\n")
  #cat(code)
  reg$cmdline = paste0("reg_fun = ", code,"\nresults=reg_fun(dat)")
  reg_fun = eval(parse(text=code))
  #debug(reg_fun)
  #dat = make_regxvar_cols(dat, regxvar)
  results = reg_fun(dat)

  ct = results$ct
  ct$cterm = cterm_of_r_coefs(ct$term,regvar, dot_to_at = TRUE)
  co_df = ct_to_regcoef(ct, lang="r",variant = mr$variant,artid = mr$artid)
  co_df$step = step

  reg$rcmd = results$rcmd
  reg$regcoef = list(co_df)

  reg$glance = results["glance"]

  mr = mr_set_step_result(mr, step, reg=reg)

  #ct$msg = msg
  #outfile = paste0(mr$step.dir, "/rreg_", step, ".Rds")
  #saveRDS(reg, outfile)
  mr
}



s2r_study_agg_fun = function(mr, ...) {
  restore.point("s2r_study_agg_fun")
  project = basename(mr$project.dir)

  # R results from metareg run
  r_regs = mr_get_steps_result(mr, "reg")

  #r_regs = mr_agg_df_rds(mr, "rreg_*.Rds", file_col="file")
  #r_regs$step = as.integer(str.between(r_regs$file, "_", "."))

  r_co = bind_rows(r_regs$regcoef)

  stata_co = mr_get_base_table(mr, "regcoef", steps = r_regs$step)

  diff_r_tab = coef_diff_table(r_co,stata_co)
  diff_r_sum = coef_diff_summary(diff_r_tab, c("all","coef"))

  inf_filter_steps = r_regs$step[r_regs$infeasible_filter]
  if (length(inf_filter_steps)>0) {
    diff_r_sum$problem[diff_r_sum$step %in% inf_filter_steps] = "stata_filter_not_translated"
  }

  glance_df = bind_rows_with_parent_fields(r_regs, "glance",c("step"))




  res = regdb_stats_to_regscalar_regstring(glance_df, variant = mr$variant, artid=mr$artid)
  regscalar = res$regscalar; regstring = res$regstring

  reg_stats = regdb_glance_to_reg_stats(glance_df)
  r_regs=left_join_overwrite(r_regs, reg_stats, by="step")
  r_regs$variant = mr$variant
  #r_regs$cmdline = ""
  r_regs$cmd = r_regs$rcmd
  r_regs$lang = "r"


  s_regs = mr_get_base_table(mr, "reg")
  regcheck = mr_get_regcheck_after_run(mr,tolerable_deviation = 1e-4, variant=mr$variant)
  regcheck = left_join_overwrite(regcheck, select(s_regs,step, cmd, se_category, se_type), by=c("step"))
  # For some commands we allow larger tolerabl deviation since
  # se are not calculated exactly the same way in R and Stata

  #rows = which(regcheck$cmd %in% c("logit","xtlogit","probit","xtprobit","dprobit"))

  #regcheck$tolerable_deviation[rows] = 0.01


  diff = diff_r_sum %>% filter(compare_what=="all")
  regcheck = left_join_overwrite(regcheck, transmute(diff,step=step,
    # Geometric mean of rel_diff and minimum of rel_diff and abs_diff
    deviation= exp(0.5+log(max_rel_diff)+0.5*log(max_deviation))),
    by="step")

  # For probit & co standard errors will not match
  # we will only use the coefs to compare
  coef_diff = diff_r_sum %>% filter(compare_what=="coef")
  regcheck = left_join_overwrite(regcheck,transmute(coef_diff,step=step,
     coef_deviation= exp(0.5+log(max_rel_diff)+0.5*log(max_deviation))), by="step")

  rows = rows = which(regcheck$cmd %in% c("logit","xtlogit","probit","xtprobit","dprobit") & regcheck$se_category == "iid")
  regcheck$deviation[rows] = regcheck$coef_deviation[rows]
  regcheck$comment[rows] = "deviation ignores se"

  mr = mr_set_header(mr, regcheck)

  s2r_details = list(
    reg = r_regs,
    regscalar = regscalar,
    regstring = regstring,
    regcoef = r_co,
    coeff_diff = diff_r_sum
  )

  s2r_core = list(
    header = mr_get_header(mr),
    regcheck = regcheck
  )

  mr = mr_save_parcels(mr, parcels = list(s2r_core = s2r_core, s2r_details=s2r_details))

  mr
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/mr_s2r.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/reg2r.R
```
# Convert to calls from lm and iv and general helper function
# to create R regression commands and execute them

reg.cmds.without.r.translation = function() {
  c("dprobit","tobit")
}

make_reg_call = function(reg,...) {
  if (reg$cmd %in% reg.cmds.without.r.translation()) {
    return(list(
      dont_run = TRUE,
      ti = reg_translation_info(s_cmd=reg$cmd, feasible=FALSE, problem="not_implemented")
    ))
  }

  if (reg$cmd == "qreg") {
    reg_call = make_quantreg_call(reg, ...)
  } else if (reg$cmd %in% c("dprobit")) {
    reg_call = make_mfx_call(reg,...)
  } else if (reg$cmd %in% "tobit") {
    reg_call = make_tobit_call(reg,...)
  } else {
    # As default use fixest
    reg_call = make_fixest_call(reg,...)
  }
  restore.point("stata.to.r.reg.call")
  reg_call
}

get.reg.opt = function(reg, opt) {
  row = which(reg$opts.df[[1]]$opt == opt)
  if (length(row)==0) return(NULL)
  reg$opts.df[[1]][row,]
}

eval_reg = function(call.li, ..., envir=parent.frame()) {
  restore.point("eval_reg_call")
  extra.args = list(...)
  args = call.li$args
  args[names(extra.args)] = extra.args
  do.call(call.li$command, args, envir = envir)
}





make_default_reg_call = function(reg,command, allow.robust=TRUE, max.cluster=0, allow.weights=TRUE, robust.arg = "robust", cluster.arg = "cluster", ...) {
  restore.point("make_default_reg_call")

  ti = reg_translation_info(reg$cmd, command)
  vi = reg$vi[[1]]
  formula = vi_to_lm_iv_formula(vi)
  args = list(formula = formula)
  if (!is.empty(reg$weights_var)) {
    if (!allow.weights) {
      ti$weights_ok = FALSE
    } else {
      args$weights = as.formula(paste0("~", reg$weights_var))
    }
  }

  se.info = reg$se.info[[1]]
  if (se.info$stata_se=="robust") {
    if (!allow.robust) {
      ti$se_ok=FALSE
      ti$se_type="robust"
    } else if (!is.null(robust.arg)) {
      args$robust = TRUE
    }
  } else if (se.info$stata_se=="cluster") {
    cluster = se.info$clustervar[[1]]
    if (length(cluster) > max.cluster) {
      ti$se_ok=FALSE
      ti$se_type = "cluster"
    } else if (!is.null(cluster.arg)) {
      args[[cluster.arg]] = cluster
    }
  }
  list(
    dont_run = isTRUE(!ti$feasible),
    command = command,
    args=args,
    ti = ti
  )
}

reg_translation_info = function(s_cmd, r_cmd="",feasible = TRUE, problem="", problem_descr="", se_ok=TRUE, se_type="", se_descr="", weights_ok=TRUE) {
  tibble(s_cmd, r_cmd, feasible, problem, problem_descr, se_ok, se_type, se_descr, weights_ok)
}




make_lm_call = function(reg, command="lm") {
  restore.point("make_lm_call")
  vi = reg$vi[[1]]
  reg_call = make_default_reg_call(reg, command)
  reg_call
}

make_lm_iv_call = function(reg) {
  restore.point("make_lm_iv_call")
  vi = reg$vi[[1]]
  is_iv = any(vi$role == "instr")
  command = if(is_iv) "ivreg" else "lm"
  reg_call = make_default_reg_call(reg, command)
  reg_call
}

vi_to_lm_iv_formula = function(vi, min_fe_level = Inf, as.character = FALSE) {
  restore.point("vi_to_lm_iv_formula")

  # Add time series prefixes like L2. or d. to variable name
  # those variables were manually added
  rows = which(toupper(substring(vi$prefix,1,1)) %in% c("D","L","F","S"))
  vi$var[rows] = paste0(vi$prefix[rows],vi$var[rows])

  depvars = vi$var[vi$role=="dep"]
  form = paste0(paste0(depvars, collapse=" + "), " ~ ")

  terms = vi_to_lm_felm_terms(vi, min_fe_level = min_fe_level)

  # Exogeneous x that are no FE
  exo.rows = which(terms$role == "exo" & terms$as_fe == FALSE)
  if (sum(exo.rows)>0) {
    form = paste0(form, paste0(terms$x_expr[exo.rows], collapse= " + "))
  } else {
    form = "0"
  }

  # instruments
  rows = which(terms$role == "instr")
  if (sum(rows)>0) {
    form = paste0(form, " | ",paste0(terms$x_expr[c(rows, exo.rows)], collapse= " + "))
  }


  if (as.character) return(form)
  as.formula(form)

}


# Deal with factor variables and interaction effects
# in default manner
vi_to_lm_felm_terms = function(vi, min_fe_level = Inf) {
  restore.point("vi_to_lm_iv_terms")

  # In stata x variables starting with o. like o.var will be omitted
  vi = vi %>%
    filter(!is.true(prefix=="o"))


  ia = vi %>%
    filter(is_ia) %>%
    vi.add.ia.type() %>%
    group_by(is_ia, ia_cterm, role, ia_num, main_pos) %>%
    summarize(
      ia_type = first(ia_type),
      fe_expr = case_when(
        ia_type %in% c("dummies","numeric") ~ NA_character_,
        ia_type == "fe" ~ paste0(var, collapse="#"),
        ia_type == "fe_numeric" ~ paste0(var[1],"#",var[2]),
        ia_type == "unknown" ~ NA_character_,
        TRUE ~ NA_character_
      )[1],
      x_expr = paste0(ifelse(!is_fe, var, paste0("factor(",var,")")), collapse= if (isTRUE(first(add_main_effects))) "*" else ":"),
      # x_expr = case_when(
      #   ia_type %in% c("dummies","numeric") ~ paste0("I(", paste0(var, collapse="*"),")"),
      #   ia_type == "fe" ~ paste0(ifelse(is_factor, var, paste0("fe(",var,")")), collapse="*"),
      #   ia_type == "fe_numeric" ~ paste0(ifelse(is_factor[1], var[1], paste0("fe(",var[1],")")),":",var[2]),
      #   ia_type == "unknown" ~ NA_character_
      # )[1],
      as_fe = case_when(
        role != "exo" ~ FALSE,
        is.na(fe_expr) ~ FALSE,
        ia_type=="fe_numeric" & distinct_num[1] < min_fe_level ~ FALSE,
        ia_distinct_num < min_fe_level ~ FALSE,
        TRUE ~ TRUE
      )[1]
    ) %>%
    ungroup()

  no_ia = vi %>%
    filter(!is_ia) %>%
    mutate(
      fe_expr = var,
      x_expr = case_when(
        is_fe & !is_factor ~ paste0("fe(", var,")"),
        TRUE ~ var
      ),
      as_fe = case_when(
        !is_fe ~ FALSE,
        role != "exo" ~ FALSE,
        distinct_num < min_fe_level ~ FALSE,
        TRUE ~ TRUE
      )
    )

  cols = c("role", "is_ia", "main_pos", "as_fe","x_expr","fe_expr")
  terms = bind_rows(ia[,cols], no_ia[cols]) %>%
    arrange(main_pos)
}


# Does not yet work nicely
make_tobit_call = function(reg, ...) {
  restore.point("make_tobit_call")
  library(AER)
  reg_call = make_default_reg_call(reg,"tobit", max.cluster=1)
  reg_call
}

tidy.tobit = function(tobit, ...) {
  mat = coeftest(tobit)
  tibble(term = rownames(mat), estimate=mat[,1], std.error = mat[,2], statistic=mat[,3], p.value = mat[,4])
}


# Does not yet work nicely
make_mfx_call = function(reg,...) {
  restore.point("make_mfx_call")

  if (reg$cmd=="dprobit") {
    command = "probitmfx"
  }
  reg_call = make_default_reg_call(reg, command, max.cluster = 2, cluster.arg = NULL)
  cluster = reg$se.info$clustervar[[1]]
  if (length(cluster)>=1) {
    reg_call$args$clustervar1 = cluster[1]
  }
  if (length(cluster)>=2) {
    reg_call$args$clustervar2 = cluster[2]
  }

  reg_call$args$atmean = TRUE
  reg_call
}



```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/reg2r.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/regvar_expand.R
```
example = function() {
  library(repboxReg)
  project.dir = "/home/rstudio/repbox/projects_reg/aer_105_5_55"
  step = 5

  dat=haven::read_dta("/home/rstudio/repbox/projects_reg/aer_105_5_55/metareg/dap/stata/cache/step_1.dta")

  dap = get.project.dap(project.dir)
  mr = dap
  internal_reg = mr_get_reg_info(mr, step,dat)
  org_dat = dat
  dat = mr_adapt_data_for_reg(project.dir, step, internal_reg, dat)

  regvar = load_parcel(project.dir, "base","regvar")$regvar %>% filter(step==5)
  regcoef = load_parcel(project.dir, "base","regcoef")$regcoef %>% filter(step==5)

  res = expand_reg_dat_cols(regvar, dat)
  erv = specify_used_reg_vars(res$eregvar, regcoef)
}

specify_used_reg_vars = function(eregvar, regcoef) {
  restore.point("specify_used_reg_vars")
  eregvar$has_coef = eregvar$cterm %in% regcoef$cterm

  if (any(!regcoef$cterm %in% c("(Intercept)",eregvar$cterm))) {
    restore.point("not all regcoef cterm")
    extra = setdiff(regcoef$cterm, c("(Intercept)",eregvar$cterm))
    stop("There are regcof cterm that are not part of the expanded regvars. Maybe the order of interaction terms differs. Please check and correct the code.")
  }
  eregvar
}




# Expands interaction effects and factors. Similar to model matrix but uses regvar information
expand_reg_dat_cols = function(regvar, dat) {
  restore.point("expand_reg_dat_cols")
  regvar = regvar[regvar$role %in% c("exo","endo","instr"),]

  rows = regvar$var_reg_type == "factor"
  factor_vars = unique(regvar$cterm[rows])

  factor_levels = lapply(factor_vars, function(var) {
    unique(dat[[var]]) %>% as.character()
  })
  names(factor_levels) = factor_vars

  ia_cterms = unique(regvar$ia_cterm)


  res_li = lapply(ia_cterms, function(ia_term) {
    rows = which(regvar$ia_cterm == ia_term)
    if (length(rows)==1) {
      if (!regvar$var_reg_type[[rows]]=="factor") return(NULL)
      cterm = regvar$cterm[rows]
      res = make_factor_level_vars(cterm,dat, level_li = factor_levels)
    } else if (length(rows)==2) {
      res = make_ia2_vars(regvar[rows,], dat,  level_li = factor_levels)
    } else if (length(rows)==3) {
      res = make_ia3_vars(regvar[rows,], dat,  level_li = factor_levels)
    } else {
      stop("Cannot yet deal with tripple interactions or more.")
    }
    res
  })

  ia_subterms = lapply(seq_along(ia_cterms), function(i) {
    ia_cterm = ia_cterms[i]
    union(regvar$cterm[regvar$ia_cterm==ia_cterm & regvar$var_reg_type!="factor"], names(res_li[[i]]))
  })
  eregvar = tibble(ia_cterm=ia_cterms, cterm = ia_subterms) %>%
    unnest(cterm) %>%
    left_join(regvar %>% select(ia_cterm, role), by="ia_cterm") %>%
    unique()

  new_dat = bind_cols(dat, bind_cols(res_li))
  dupl = duplicated(colnames(new_dat))
  new_dat = new_dat[,!dupl]
  new_dat

  list(eregvar=eregvar, dat=new_dat)
}

make_ia2_vars = function(rv, dat, level_li) {
  restore.point("make_ia2_vars")

  factor_rows = which(rv$var_reg_type == "factor")
  if (length(factor_rows)>0) {
    fdat = lapply(rv$cterm[factor_rows],make_factor_level_vars, dat=dat, level_li=level_li) %>%
      bind_cols()
  } else {
    fdat = NULL
  }

  cterm1 = rv$cterm[1]
  cterm2 = rv$cterm[2]

  is_factor1 = rv$var_reg_type[1]=="factor"
  is_factor2 = rv$var_reg_type[2]=="factor"

  if (is_factor1) {
    vars1 = paste0(cterm1,"=", level_li[[cterm1]])
  } else {
    vars1 = cterm1
  }

  if (is_factor2) {
    vars2 = paste0(cterm2,"=", level_li[[cterm2]])
  } else {
    vars2 = cterm2
  }

  grid = expand.grid(var1=vars1, var2=vars2,stringsAsFactors = FALSE) %>%
    mutate(var12 = sort2_chr(var1, var2, sep="#"))

  dat12_li = lapply(seq_len(nrow(grid)), function(i) {
    if (is_factor1) {
      val1 = fdat[[grid$var1[i]]]
    } else {
      val1 = dat[[grid$var1[i]]]
    }
    if (is_factor2) {
      val2 = fdat[[grid$var2[i]]]
    } else {
      val2 = dat[[grid$var2[i]]]
    }
    val1*val2
  })
  names(dat12_li) = grid$var12
  dat12 = as_tibble(dat12_li)

  if (is.null(rv$add_main_effects) || isTRUE(rv$add_main_effects[1])) {
    return(bind_cols(fdat, dat12))
  } else {
    return(dat12)
  }
}

# FILE: regtranslate/regvar_expand.R
make_ia3_vars = function(rv, dat, level_li) {
  restore.point("make_ia3_vars")

  factor_rows = which(rv$var_reg_type == "factor")
  if (length(factor_rows)>0) {
    fdat = lapply(rv$cterm[factor_rows], make_factor_level_vars, dat=dat, level_li=level_li) %>%
      bind_cols()
  } else {
    fdat = NULL
  }

  is_f1 = rv$var_reg_type[1]=="factor"
  is_f2 = rv$var_reg_type[2]=="factor"
  is_f3 = rv$var_reg_type[3]=="factor"

  vars1 = if (is_f1) paste0(rv$cterm[1],"=", level_li[[rv$cterm[1]]]) else rv$cterm[1]
  vars2 = if (is_f2) paste0(rv$cterm[2],"=", level_li[[rv$cterm[2]]]) else rv$cterm[2]
  vars3 = if (is_f3) paste0(rv$cterm[3],"=", level_li[[rv$cterm[3]]]) else rv$cterm[3]

  # 2-way grids
  g12 = expand.grid(a=vars1, b=vars2, stringsAsFactors=FALSE) %>% mutate(res = sort2_chr(a, b, sep="#"))
  g13 = expand.grid(a=vars1, b=vars3, stringsAsFactors=FALSE) %>% mutate(res = sort2_chr(a, b, sep="#"))
  g23 = expand.grid(a=vars2, b=vars3, stringsAsFactors=FALSE) %>% mutate(res = sort2_chr(a, b, sep="#"))

  # 3-way grid
  g123 = expand.grid(a=vars1, b=vars2, c=vars3, stringsAsFactors=FALSE) %>%
    mutate(res = split_and_sort(paste0(a, "#", b, "#", c), split="#", k=3L))

  # Compute values
  get_val = function(is_f, grid_col, i) if (is_f) fdat[[grid_col[i]]] else dat[[grid_col[i]]]

  dat12 = as_tibble(setNames(lapply(seq_len(nrow(g12)), function(i) get_val(is_f1, g12$a, i) * get_val(is_f2, g12$b, i)), g12$res))
  dat13 = as_tibble(setNames(lapply(seq_len(nrow(g13)), function(i) get_val(is_f1, g13$a, i) * get_val(is_f3, g13$b, i)), g13$res))
  dat23 = as_tibble(setNames(lapply(seq_len(nrow(g23)), function(i) get_val(is_f2, g23$a, i) * get_val(is_f3, g23$b, i)), g23$res))
  dat123 = as_tibble(setNames(lapply(seq_len(nrow(g123)), function(i) get_val(is_f1, g123$a, i) * get_val(is_f2, g123$b, i) * get_val(is_f3, g123$c, i)), g123$res))

  if (is.null(rv$add_main_effects) || isTRUE(rv$add_main_effects[1])) {
    return(bind_cols(fdat, dat12, dat13, dat23, dat123))
  } else {
    return(dat123)
  }
}

make_factor_level_vars = function(var,dat, levels = level_li[[var]],level_li) {
  restore.point("make_factor_level_vars")
  cterms = paste0(var, "=", levels)
  vals = lapply(seq_along(levels), function(i) {
    1L*(dat[[var ]]==levels[i])
  })
  names(vals) = cterms
  as_tibble(vals)
  #list(info=tibble(cterm=cterm), dat=vals)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/regvar_expand.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/repbox.R
```
# These functions provide more direct interfaces usable in connection with
# repbox projects

repbox_load_regtranslate_parcels = function(project_dir, parcels = list()) {
  library(repboxDB)
  parcels = repdb_load_parcels(project_dir,c("reg_core","regvar","regxvar","cmdpart"), parcels=parcels)

}

mr_load_regtranslate_parcels = function(mr) {
  mr$parcels = repbox_load_regtranslate_parcels(mr$project_dir, mr$parcels)
  mr
}

mr_reg_stata_to_r_formula = function(mr, step, prefer="fixest", opts=code_options()) {

  repbox_reg_stata_to_r_code(mr$project_dir, step, mr$parcels, prefer=prefer, opts=opts, just_formula = TRUE)
}

mr_reg_stata_to_r_code = function(mr, step, prefer="fixest", opts=code_options()) {
  repbox_reg_stata_to_r_code(mr$project_dir, step, mr$parcels, prefer=prefer, opts=opts)
}

repbox_reg_stata_to_r_code = function(project_dir, steps=NULL, parcels, prefer="fixest", opts=code_options(), just_formula=FALSE) {
  restore.point("repbox_reg_stata_to_r_code")
  reg = parcels$reg_core$reg
  regvar = parcels$regvar$regvar
  regxvar = parcels$regxvar$regxvar
  cmdpart = parcels$cmdpart$cmdpart

  if (is.null(steps)) steps = reg$step


  reg = reg %>% filter(step %in% steps)
  regvar = regvar %>% filter(step %in% steps)
  regxvar = regxvar %>% filter(step %in% steps)
  cmdpart = cmdpart %>% filter(step %in% steps)

  if (just_formula) {
    return(reg_stata_to_r_formula(reg, regvar, regxvar, cmdpart, prefer=prefer, opts=opts))
  }
  reg_stata_to_r_code(reg, regvar, regxvar, cmdpart, prefer=prefer, opts=opts)

}


```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/repbox.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/s2r_repex.R
```
# Helper functions for investigation

example = function() {
  library(repboxReg)
  library(regtranslate)
  project.dir = "~/repbox/projects_reg/testsupp"
  project.dir = "/home/rstudio/repbox/projects_reg/jpe_125_1_9"

  reg_core = load_parcel(project.dir,"base","reg_core")

  core = load_parcel(project.dir,"s2r","s2r_core")

  regcheck = core$regcheck %>% left_join(reg_core$reg %>% select(cmd,step),by="step") %>% arrange(desc(deviation))
  head(regcheck)
  s2r_repex(project.dir, step=10)
  navigate_to_repex(project.dir)
}

#' Generates a folder with a reproducible example that shall help
#' detect why an R translation yields different results than the Stata version.
s2r_repex = function(project.dir, step,
                     repex.dir = file.path(project.dir,"metareg","s2r","repex", step),
                     parcels=load_parcels(project.dir, c("base","s2r"),just_glob = c("detail","core","regcoef", "source","regvar","regxvar"), ignore_glob = "org_"),
                     dap=get.project.dap(project.dir, make.if.missing=FALSE)
) {
  restore.point("s2r_reprex")

  if (!dir.exists(repex.dir)) dir.create(repex.dir,recursive = TRUE)

  sparcels = filter_parcels_by_step(parcels, step)

  scode = stata_code_reg_data_preparation(project.dir,step, dap,add_reg_code = TRUE)


  rcode_prep = r_code_reg_data_preparation(project.dir,step, dap)
  reg_df = parcels$s2r_details$reg
  rreg = reg_df[reg_df$step==step,]
  rcode_reg = rreg$cmdline

  # Remove function stuff
  rcode_reg = sep.lines(rcode_reg)
  rcode_reg = rcode_reg[-c(1:2, length(rcode_reg)-(0:3))]
  rcode_reg = merge.lines(rcode_reg)
  #cat(rcode_reg)


  rcode = paste0(
    "# R code to replicate analysis in step ", step,"\n",
    'setwd("',repex.dir,'")',
    rcode_prep,
    '
sp = readRDS("step_parcels.Rds")
regxvar = sp$regxvar$regxvar
regvar = sp$regvar$regvar

dat = create_cterm_cols(dat, unique(regvar$cterm))
dat = make_regxvar_cols(dat, regxvar)
\n',
    rcode_reg,
    "\n\nct")

  # Add further R analysis code

  saveRDS(sparcels,file.path(repex.dir,"step_parcels.Rds"))

  rcode = paste0(rcode, '
regvar = sp$regvar$regvar
co = ct_to_regcoef(ct, "r", regvar=regvar)

r_co = sp$s2r_details$regcoef
s_co = sp$regcoef$regcoef

coef_diff = nice_coef_diff(r_co, s_co, labs=c("r","s")) %>%
  left_join(select(co, coef, cterm), by="cterm")
coef_diff
co

navigate_to_repex("',project.dir,'")
')
  si = sparcels$regsource$regsource
  source.file = file.path(project.dir,"mod",si$script_path)
  source_code = paste0('
# Source: Line ', si$code_line_start, ' in ', source.file,'
# rstudioapi::navigateToFile("', source.file,'")
')
  rcode = paste0(rcode, source_code)

  # Write files
  if (!dir.exists(repex.dir)) dir.create(repex.dir, recursive = TRUE)

  writeLines(rcode, file.path(repex.dir,paste0("rcode.R")))
  writeLines(scode, file.path(repex.dir,"stata_code.do"))


  rp_code = make_repex_project_code(project.dir, repex.dir)
  rp_code = paste0(rp_code, "\n  mr = mr_s2r_study(project.dir)")
  writeLines(rp_code, file.path(repex.dir,"repex_project.R"))


  cat("\nReproducible example written to ",repex.dir,"\n")
  invisible()
}

```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/s2r_repex.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/se.R
```

# Old code: possible can be replaced sometime using
# cmdpart. But not yet done.
regdb_parse_se_args = function(se_args, as_df=FALSE) {
  restore.point("regdb_parse_se_args")
  #se_args = c("cluster1=i1;cluster2=i2","cluster2=i2")[1]
  if (length(se_args)>1) {
    stop("regdb_se_args_to_list is not yet vectorized.")
  }

  str = strsplit(se_args,";", fixed=TRUE)[[1]]
  eq_pos = stri_locate_first_fixed(str,"=")[,1]
  var = substring(str,1,eq_pos-1)
  val = substring(str,eq_pos+1)
  if (!as_df) {
    names(val) = var
    return(val)
  }
  tibble(arg_name=var, arg_val=val)
}


regdb_se_to_sandwich = function(se_category, se_type, se_args,reg_info=NULL) {

  restore.point("regdb_se_to_sandwich")

  se_category = tolower(trimws(as.character(se_category[1])))
  se_type = tolower(trimws(as.character(se_type[1])))

  if (
    length(se_args) == 0 ||
    is.na(se_args[1]) ||
    !nzchar(se_args[1])
  ) {
    se_args = ""
    args = character(0)
  } else {
    se_args = as.character(se_args[1])

    if (stri_detect_fixed(se_args, "=")) {
      args = repdb_parse_se_args(se_args)
    } else {
      args = setNames(se_args, "raw")
    }
  }

  get_arg = function(name, default=NA_character_) {
    if (!name %in% names(args)) {
      return(default)
    }

    val = as.character(args[name][1])

    if (is.na(val) || !nzchar(val)) {
      return(default)
    }

    val
  }

  is_true_arg = function(name, default=FALSE) {
    val = get_arg(name)

    if (is.na(val)) {
      return(default)
    }

    tolower(val) %in% c("true", "t", "yes", "y", "1")
  }

  reg_field = function(name) {
    if (
      is.null(reg_info) ||
      !name %in% names(reg_info) ||
      length(reg_info[[name]]) == 0
    ) {
      return("")
    }

    val = as.character(reg_info[[name]][1])

    if (is.na(val)) {
      return("")
    }

    trimws(val)
  }

  formula_code = function(vars) {
    vars = as.character(vars)
    vars = vars[!is.na(vars) & nzchar(vars)]

    if (length(vars) == 0) {
      return("")
    }

    vars = paste0("`", vars, "`")

    paste0(
      "~ ",
      stri_flatten(vars, collapse=" + ")
    )
  }

  cluster_vars = function() {
    if (length(args) == 0 || is.null(names(args))) {
      return(character(0))
    }

    arg_names = names(args)
    rows = which(stri_startswith_fixed(arg_names, "cluster"))

    if (length(rows) == 0) {
      return(character(0))
    }

    cluster_names = arg_names[rows]
    cluster_num = suppressWarnings(as.integer(
      stri_extract_first_regex(cluster_names, "[0-9]+$")
    ))

    rows = rows[order(cluster_num, na.last=TRUE)]
    vars = as.character(args[rows])

    vars[!is.na(vars) & nzchar(vars)]
  }

  unsupported_code = function(msg) {
    repbox_problem(
      msg,
      "sandwich_se_not_implemented",
      fail_action="msg"
    )

    paste0(
      "stop(",
      encodeString(msg, quote='"'),
      ")"
    )
  }

  finite_sample_factor = function(code) {
    paste0(
      "(",
      code,
      ") * stats::nobs(reg) / ",
      "(stats::nobs(reg) - sum(!is.na(stats::coef(reg))))"
    )
  }

  small = is_true_arg("small")

  # Conventional, OIM, and other model-based covariance estimators.
  #
  # reg is estimated with vcov = "iid" before this expression is evaluated,
  # so stats::vcov(reg) returns the model-based covariance matrix.
  if (
    se_category == "iid" ||
    se_type %in% c(
      "iid", "unadjusted", "conventional", "ols", "oim"
    )
  ) {
    return("stats::vcov(reg)")
  }

  # The OPG covariance is the inverse outer product of the score vectors.
  if (se_type == "opg") {
    return(paste0(
      "sandwich::vcovOPG(reg, adjust = ",
      if (small) "TRUE" else "FALSE",
      ")"
    ))
  }

  clustervar = cluster_vars()
  is_cluster = se_category == "cluster" ||
    se_type %in% c("cluster", "twoway", "multiway")

  # Cluster-robust covariance estimators.
  if (is_cluster) {
    if (length(clustervar) == 0) {
      return(unsupported_code(
        paste0(
          "Cannot construct cluster-robust covariance matrix: ",
          "no clustering variable is stored in se_args."
        )
      ))
    }

    cluster_fml = formula_code(clustervar)

    # sandwich::vcovCL supports HC0-HC3 corrections. HC2 and HC3
    # with a cluster variable correspond to CR2-style and CR3-style
    # cluster leverage corrections.
    if (se_type %in% c("hc0", "hc1", "hc2", "hc3")) {
      hc_type = toupper(se_type)
    } else {
      # HC1 plus cadjust gives the usual observation and cluster
      # finite-sample corrections used by standard Stata cluster VCEs.
      hc_type = "HC1"
    }

    if (se_type %in% c("hc4", "hc5")) {
      return(unsupported_code(
        paste0(
          "sandwich::vcovCL does not implement clustered ",
          toupper(se_type),
          " covariance matrices."
        )
      ))
    }

    if (is_true_arg("hansen")) {
      repbox_problem(
        paste0(
          "The Stata Hansen correction for clustered HC3 is not ",
          "implemented by sandwich::vcovCL. Use the standard HC3 ",
          "cluster correction."
        ),
        "sandwich_hansen_not_implemented",
        fail_action="msg"
      )
    }

    return(paste0(
      "sandwich::vcovCL(",
      "reg, ",
      "cluster = ", cluster_fml, ", ",
      'type = "', hc_type, '", ',
      "cadjust = TRUE",
      ")"
    ))
  }

  # Observation-level heteroskedasticity-consistent covariance estimators.
  if (se_type %in% c(
    "hc0", "hc1", "hc2", "hc3", "hc4", "hc5"
  )) {
    return(paste0(
      "sandwich::vcovHC(",
      "reg, ",
      'type = "', toupper(se_type), '"',
      ")"
    ))
  }

  # A generic robust type does not identify a particular HC correction.
  # sandwich::sandwich() is the unadjusted empirical score sandwich.
  if (
    se_category == "robust" &&
    se_type %in% c("robust", "")
  ) {
    code = "sandwich::sandwich(reg)"

    if (small) {
      code = finite_sample_factor(code)
    }

    return(code)
  }

  # Stata newey uses a Bartlett-kernel Newey-West covariance estimator
  # without prewhitening. NeweyWest(..., adjust=TRUE) applies the
  # regression-style n/(n-k) finite-sample correction.
  if (se_type %in% c("nw", "neweywest", "newey-west")) {
    lag = get_arg("lag")

    if (is.na(lag) || !stri_detect_regex(lag, "^[0-9]+$")) {
      return(unsupported_code(
        paste0(
          "Cannot construct Newey-West covariance matrix: ",
          "a nonnegative integer lag is required in se_args."
        )
      ))
    }

    timevar = reg_field("timevar")
    order_code = ""

    if (nzchar(timevar)) {
      order_code = paste0(
        ", order.by = ",
        formula_code(timevar)
      )
    }

    return(paste0(
      "sandwich::NeweyWest(",
      "reg, ",
      "lag = ", lag, ", ",
      "prewhite = FALSE, ",
      "adjust = TRUE",
      order_code,
      ")"
    ))
  }

  # A generic HAC label does not contain enough information to reproduce
  # a particular Stata kernel and bandwidth. vcovHAC provides a generic
  # HAC estimator, but a stored raw hacspec is reported as an approximation.
  if (se_type == "hac") {
    hacspec = get_arg("hacspec")

    if (!is.na(hacspec)) {
      repbox_problem(
        paste0(
          "The stored HAC specification '", hacspec,
          "' is not translated exactly. Use sandwich::vcovHAC ",
          "with its default HAC weighting."
        ),
        "sandwich_hac_approximation",
        fail_action="msg"
      )
    }

    timevar = reg_field("timevar")
    order_code = ""

    if (nzchar(timevar)) {
      order_code = paste0(
        ", order.by = ",
        formula_code(timevar)
      )
    }

    return(paste0(
      "sandwich::vcovHAC(",
      "reg, ",
      "prewhite = FALSE, ",
      "adjust = TRUE",
      order_code,
      ")"
    ))
  }

  # sandwich::vcovPL with aggregate=TRUE computes Driscoll-Kraay:
  # score contributions are aggregated by time before applying the
  # HAC correction, allowing cross-sectional and serial dependence.
  if (se_type %in% c("dk", "dkraay", "driscoll-kraay")) {
    panelvar = reg_field("panelvar")
    timevar = reg_field("timevar")

    if (!nzchar(panelvar) || !nzchar(timevar)) {
      return(unsupported_code(
        paste0(
          "Cannot construct Driscoll-Kraay covariance matrix: ",
          "panelvar and timevar are required."
        )
      ))
    }

    lag = get_arg("lag")
    lag_code = ""

    if (!is.na(lag)) {
      if (stri_detect_regex(lag, "^[0-9]+$")) {
        lag_code = paste0(", lag = ", lag)
      } else if (lag %in% c("max", "NW1987", "NW1994")) {
        lag_code = paste0(
          ", lag = ",
          encodeString(lag, quote='"')
        )
      } else {
        return(unsupported_code(
          paste0(
            "Unsupported Driscoll-Kraay lag specification: ",
            lag
          )
        ))
      }
    }

    return(paste0(
      "sandwich::vcovPL(",
      "reg, ",
      "cluster = ",
      formula_code(c(panelvar, timevar)),
      lag_code, ", ",
      "aggregate = TRUE, ",
      "adjust = TRUE",
      ")"
    ))
  }

  # Basic case-resampling covariance estimator. Recognized arguments are
  # reps and cluster1, cluster2, etc. Other Stata bootstrap options are
  # not reproduced here.
  if (se_type == "bootstrap") {
    reps = get_arg("reps")
    cluster_code = ""
    reps_code = ""

    if (length(clustervar) > 0) {
      cluster_code = paste0(
        ", cluster = ",
        formula_code(clustervar)
      )
    }

    if (!is.na(reps) && stri_detect_regex(reps, "^[0-9]+$")) {
      reps_code = paste0(", R = ", reps)
    }

    return(paste0(
      "sandwich::vcovBS(",
      "reg",
      cluster_code,
      reps_code,
      ")"
    ))
  }

  # The sandwich jackknife drops one observation, or one cluster when a
  # clustering variable is supplied, and recomputes the estimates.
  if (se_type == "jackknife") {
    cluster_code = ""

    if (length(clustervar) > 0) {
      cluster_code = paste0(
        ", cluster = ",
        formula_code(clustervar)
      )
    }

    return(paste0(
      "sandwich::vcovJK(",
      "reg",
      cluster_code,
      ")"
    ))
  }

  unsupported_code(paste0(
    "No sandwich covariance translation is implemented for ",
    "se_category = '", se_category,
    "' and se_type = '", se_type, "'."
  ))
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/se.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/split_n_sort.R
```
sort2_chr = function(a, b, ..., sep=NULL) {
  swap = stringi::stri_cmp_gt(a, b, ...)
  lo = ifelse(swap, b, a)
  hi = ifelse(swap, a, b)
  if (!is.null(sep)) return(paste0(lo,sep,hi))
  list(lo = lo, hi = hi)
}

sort3_chr = function(a, b, c, ..., sep=NULL) {
  s = sort2_chr(a, b, ...)
  a = s$lo
  b = s$hi

  s = sort2_chr(b, c, ...)
  b = s$lo
  c = s$hi

  s = sort2_chr(a, b, ...)
  a = s$lo
  b = s$hi

  if (!is.null(sep)) return(paste0(a,sep,b,sep,c))

  list(a = a, b = b, c = c)
}

split_and_sort = function(terms, split = "#", ..., k = NULL) {
  if (!length(terms)) {
    return(character())
  }

  if (is.null(k)) {
    n_tok = stringi::stri_count_fixed(terms, split) + 1L
    same_k = length(unique(n_tok)) == 1L
    if (same_k) {
      k = n_tok[1]
    } else {
      k = NA_integer_
    }
  }

  if (identical(k, 2L)) {
    m = stringi::stri_split_fixed(terms, split, simplify = TRUE)
    s = sort2_chr(m[, 1], m[, 2], ..., sep=split)
    return(s)
    #return(stringi::stri_join(s$lo, s$hi, sep = split))
  }

  if (identical(k, 3L)) {
    m = stringi::stri_split_fixed(terms, split, simplify = TRUE)
    s = sort3_chr(m[, 1], m[, 2], m[, 3], ..., sep=split)
    return(s)
    return(stringi::stri_join(s$a, s$b, s$c, sep = split))
  }

  x = stringi::stri_split_fixed(terms, split, simplify = FALSE)
  vapply(
    x,
    function(tok) stringi::stri_flatten(stringi::stri_sort(tok, ...), collapse = split),
    character(1)
  )
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/split_n_sort.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_fixest.R
```

# Replace stata_to_r_code_fixest and fixest_vcov_code_from_regdb
stata_to_r_code_fixest = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_fixest")

  org_depvars = regvar$cterm[regvar$role=="dep"]
  mod_depvars = replace_cterm_special_symbols(org_depvars)

  formula = regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)

  vcov_type = fixest_vcov_type_from_regdb(reg$se_type, reg$se_args, reg$se_category)
  ssc_expr = fixest_ssc_code_from_reg(reg, vcov_type = vcov_type)
  use_ssc = !is.null(ssc_expr)

  use_sandwich = (vcov_type == "sandwich") | opts$prefer_sandwich
  use_summary = use_sandwich | opts$prefer_summary

  if (use_sandwich) {
    reg_vcov = "iid"
    vcov = regdb_se_to_sandwich(reg$se_category, reg$se_type, reg$se_args, reg_info=reg)
  } else {
    reg_vcov = fixest_vcov_code_from_regdb(reg$se_type, reg$se_args, vcov_type, quote=FALSE, reg=reg)
    if (use_summary) {
      vcov = reg_vcov
    }
  }

  command = "feols"
  arg_str = NULL
  if (reg$cmd %in% c("ppmlhdfe", "poisson", "xtpoisson")) {
    command = "fepois"
  } else if (reg$cmd %in% c("nbreg", "gnbreg")) {
    command = "fenegbin"
  } else if (reg$cmd %in% c("logit","xtlogit", "clogit")) {
    command = "feglm"
    arg_str = "family=binomial()"
  } else if (reg$cmd %in% c("probit","xtprobit","dprobit")) {
    command = "feglm"
    arg_str = 'family=binomial(link = "probit")'
  }

  arg_str = c(
    paste0("fml = formula"),
    paste0("data = dat"),
    paste0("vcov = reg_vcov"),
    arg_str
  )

  # Pass ssc to fixest natively when relevant.
  if (use_ssc) {
    arg_str = c(arg_str, "ssc = ssc")
  }

  # Handle singleton observations according to Stata behavior
  if (isTRUE(opts$match_stata_singletons)) {
    if (reg$cmd %in% c("areg", "xtreg", "xtivreg", "xtivreg2", "xtpoisson", "xtlogit", "xtprobit", "clogit")) {
      arg_str = c(arg_str, 'fixef.rm = "none"')
    } else if (reg$cmd %in% c("reghdfe", "ivreghdfe", "ppmlhdfe")) {
      # reghdfe/ppmlhdfe drops them by default, but allows keepsingletons option
      keep_singletons = FALSE
      if (!is.null(cmdpart)) {
        keep_singletons = any(cmdpart$part == "opt" & startsWith(tolower(cmdpart$content), "keepsingleton"))
      }
      if (keep_singletons) {
        arg_str = c(arg_str, 'fixef.rm = "none"')
      }
    }
  }

  library_code = "library(fixest)"
  rcmd_code = paste0('rcmd = "',command,'"')
  if (all(org_depvars==mod_depvars)) {
    data_code = ""
  } else {
    data_code = paste0(
      'dat[["', mod_depvars,'"]] = dat[["', org_depvars,'"]]',
      collapse="\n"
    )
  }

  # Apply explicit listwise deletion to emulate Stata's e(sample)
  lw_code = r_listwise_deletion_code(regvar)
  if (nzchar(lw_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", lw_code) else lw_code
  }

  is_binary = reg$cmd %in% c("logit", "xtlogit", "probit", "xtprobit", "dprobit", "clogit", "logistic", "exlogistic", "blogit", "glogit", "binreg")

  if (is_binary && isTRUE(opts$drop_perfect_predictors)) {
    # Check all possible expanded predictors before filtering omitted formulas
    pred_cols = unique(regxvar$cterm)
    pred_cols = setdiff(pred_cols, c("(Intercept)", ""))
    if (length(pred_cols) > 0) {
      pred_str = paste0('c(', paste0('"', pred_cols, '"', collapse=", "), ')')
      dp_code = paste0(
        'dp_cols = intersect(', pred_str, ', colnames(dat))\n',
        'dp_res = regtranslate::stata_drop_perfect_predictors(dat, "', mod_depvars[1], '", dp_cols, verbose = TRUE)\n',
        'dat = dp_res$dat'
      )
      data_code = paste0(data_code, "\n", dp_code)
    }
  }

  # Apply dynamic weights via centralized helper
  wt = r_weight_code(reg, template = "~ `%s`")
  if (nzchar(wt$data_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", wt$data_code) else wt$data_code
  }
  if (nzchar(wt$weight_arg)) {
    arg_str = c(arg_str, wt$weight_arg)
  }

  ssc_code = if (use_ssc) paste0("ssc = ", ssc_expr) else NULL
  formula_code = paste0("formula = ", formula)
  reg_vcov_code = paste0("reg_vcov = ", quote_arg(reg_vcov))
  reg_code = paste0("reg = ", command, "(", paste0(arg_str, collapse=","), ")")

  code_df = tibble(
    part = c("library", "rcmd", "data", "formula", if (use_ssc) "ssc", "reg_vcov", "reg"),
    code = c(library_code, rcmd_code, data_code, formula_code, if (use_ssc) ssc_code, reg_vcov_code, reg_code)
  )

  if (use_summary) {
    sum_vcov_code = paste0("sum_vcov = ", quote_arg(vcov))
    sum_code = "sum = summary(reg, vcov = sum_vcov)"
    code_df = bind_rows(
      code_df,
      tibble(part = c("sum_vcov","sum"), code = c(sum_vcov_code, sum_code))
    )
  }
  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=use_summary, use_conf_int=TRUE)
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}



fixest_vcov_code_from_regdb = function(se_type, se_args, vcov_type=fixest_vcov_type_from_regdb(se_type,se_args), quote=TRUE, reg=NULL) {
  restore.point("fixest_vcov_code_from_regdb")

  if (vcov_type %in% c("cluster","twoway", "multiway")) {
    clustervar = extract_clustervar_from_se_args(se_args)
    # Return as a formula (~ var1 + var2 + ...) natively supported by fixest
    code = paste0("~ ", paste0("`", clustervar, "`", collapse = " + "))
    return(code)
  }
  if (vcov_type %in% c("DK","NW")) {
    lag = NA_character_
    if (!is.na(se_args) && nzchar(se_args)) {
      args = regdb_parse_se_args(se_args)
      if ("lag" %in% names(args)) lag = args["lag"]
    }

    timevar = if (!is.null(reg) && !is.na(reg$timevar[1]) && nzchar(reg$timevar[1])) reg$timevar[1] else ""
    panelvar = if (!is.null(reg) && !is.na(reg$panelvar[1]) && nzchar(reg$panelvar[1])) reg$panelvar[1] else ""

    p_and_t = ""
    if (panelvar != "" && timevar != "") {
      p_and_t = paste0("`", panelvar, "` + `", timevar, "`")
    } else if (timevar != "") {
      p_and_t = paste0("`", timevar, "`")
    } else if (panelvar != "") {
      p_and_t = paste0("`", panelvar, "`")
    }

    lag_str = ""
    if (!is.na(lag) && lag != "") {
      lag_str = paste0("(", lag, ")")
    }

    if (p_and_t != "") {
      return(paste0(vcov_type, lag_str, " ~ ", p_and_t))
    } else {
      if (lag_str == "") {
        if (quote) return(paste0('"', vcov_type, '"'))
        return(vcov_type)
      } else {
        return(paste0(vcov_type, lag_str))
      }
    }
  }
  if (quote) return(paste0('"',vcov_type,'"'))
  return(vcov_type)
}



fixest_vcov_type_from_regdb = function(se_type, se_args,se_category=NA_character_) {

  restore.point("fixest_vcov_type_from_regdb ")

  se_type = tolower(trimws(as.character(se_type[1])))
  se_category = tolower(trimws(as.character(se_category[1])))

  if (is.na(se_type)) se_type = ""
  if (is.na(se_category)) se_category = ""

  clustervar = tryCatch(
    extract_clustervar_from_se_args(se_args),
    error = function(e) character(0)
  )
  clustervar = as.character(clustervar)
  clustervar = clustervar[!is.na(clustervar) & nzchar(clustervar)]

  num_clustervar = length(clustervar)
  is_cluster = se_category == "cluster" || num_clustervar > 0

  cluster_vcov_type = function() {
    if (num_clustervar <= 1) return("cluster")
    if (num_clustervar == 2) return("twoway")
    "multiway"
  }

  # Conventional and model-based VCEs are represented by fixest's
  # native model-based covariance matrix.
  if (se_type %in% c(
    "iid", "unadjusted", "conventional", "ols", "oim"
  )) {
    return("iid")
  }

  # fixest implements HC1 under the names hetero, HC1, and White.
  # Small-sample corrections are handled separately through ssc.
  if (se_type %in% c("robust", "hc1")) {
    return("hetero")
  }

  # Ordinary one-way and multiway clustering are handled natively.
  # fixest_vcov_code_from_regdb() converts these routing values into
  # a formula containing the stored cluster variables.
  if (se_type %in% c("cluster", "twoway", "multiway")) {
    return(se_type)
  }

  # fixest implements these time-series, panel, and spatial VCEs natively.
  if (se_type %in% c("nw", "neweywest", "newey-west")) {
    return("NW")
  }

  if (se_type %in% c(
    "dk", "dkraay", "driscoll-kraay", "driscoll_kraay"
  )) {
    return("DK")
  }

  if (se_type == "conley") {
    return("conley")
  }

  # These explicit nonclustered HC estimators are not native fixest
  # VCOV types. They can be computed by sandwich::vcovHC().
  if (se_type %in% c("hc0", "hc2", "hc3", "hc4", "hc5")) {
    if (!is_cluster) {
      return("sandwich")
    }

    # Clustered HC2 and HC3 are CR2/CR3-style leverage-adjusted
    # cluster VCEs. sandwich::vcovCL documents HC2/HC3 only for lm
    # and glm objects, so use ordinary fixest clustering as fallback.
    repbox_problem(
      paste0(
        "The clustered ", toupper(se_type),
        " covariance estimator is not translated exactly. ",
        "Use ordinary fixest cluster-robust standard errors."
      ),
      "fixest_cluster_hc_fallback",
      "msg"
    )
    return(cluster_vcov_type())
  }

  # OPG and generic HAC explicitly imply covariance estimators that are
  # not available as native fixest VCOV types. Use the sandwich path.
  if (se_type %in% c("opg", "hac")) {
    return("sandwich")
  }

  # sandwich implements bootstrap and jackknife covariance estimators,
  # but they need not reproduce Stata's exact resampling design and can
  # be expensive. By default use the corresponding asymptotic fixest VCE.
  # opts$prefer_sandwich can still explicitly request the resampling path.
  if (se_type %in% c("bootstrap", "jackknife")) {
    if (is_cluster && num_clustervar > 0) {
      fallback = cluster_vcov_type()
    } else {
      fallback = "hetero"
    }

    repbox_problem(
      paste0(
        "Stata ", se_type,
        " standard errors are not reproduced by default. Use ",
        fallback,
        " as an asymptotic fixest fallback."
      ),
      "fixest_resampling_vcov_fallback",
      "msg"
    )
    return(fallback)
  }

  # Survey VCEs generally account for heteroskedasticity and potentially
  # clustering. Without the complete survey design, use clustering when
  # cluster variables are stored and heteroskedasticity-robust otherwise.
  if (se_type == "svy") {
    if (is_cluster && num_clustervar > 0) {
      fallback = cluster_vcov_type()
    } else {
      fallback = "hetero"
    }

    repbox_problem(
      paste0(
        "The complete Stata survey design is unavailable. Use ",
        fallback,
        " as the fixest VCOV fallback."
      ),
      "fixest_svy_vcov_fallback",
      "msg"
    )
    return(fallback)
  }

  # Rubin's multiple-imputation variance cannot be reconstructed from a
  # single fixest estimation. The model-based VCE is the neutral fallback.
  if (se_type == "mi") {
    repbox_problem(
      paste0(
        "Multiple-imputation variance combination is not implemented. ",
        "Use fixest iid standard errors."
      ),
      "fixest_mi_vcov_fallback",
      "msg"
    )
    return("iid")
  }

  # For unknown exact types, retain the broad RepDB category where that
  # gives a runnable and economically meaningful approximation.
  if (se_category == "iid") {
    return("iid")
  }

  if (se_category == "robust") {
    repbox_problem(
      paste0(
        "Unknown robust standard error type '", se_type,
        "'. Use fixest heteroskedasticity-robust standard errors."
      ),
      "unknown_fixest_robust_vcov",
      "msg"
    )
    return("hetero")
  }

  if (se_category == "cluster" && num_clustervar > 0) {
    fallback = cluster_vcov_type()

    repbox_problem(
      paste0(
        "Unknown clustered standard error type '", se_type,
        "'. Use ordinary ", fallback,
        " cluster-robust standard errors."
      ),
      "unknown_fixest_cluster_vcov",
      "msg"
    )
    return(fallback)
  }

  # No reliable information about the VCE remains. IID is preferable to
  # invoking an unrelated sandwich estimator merely because it is robust.
  repbox_problem(
    paste0(
      "No fixest VCOV mapping is implemented for standard error type '",
      se_type, "'. Use iid standard errors."
    ),
    "unknown_fixest_vcov",
    "msg"
  )
  return("iid")
}

# Choose default fixest::ssc() settings for translated Stata commands.
# This centralizes command-specific small sample correction choices.
# Choose default fixest::ssc() settings for translated Stata commands.
# This centralizes command-specific small sample correction choices.
fixest_ssc_code_from_reg = function(reg, vcov_type = fixest_vcov_type_from_regdb(reg$se_type, reg$se_args)) {
  restore.point("fixest_ssc_code_from_reg")

  is_ml = reg$cmd %in% c("logit", "xtlogit", "probit", "xtprobit", "dprobit", "poisson", "xtpoisson", "nbreg", "gnbreg", "clogit")

  if (vcov_type %in% c("cluster", "twoway", "multiway", "DK", "NW")) {
    if (reg$cmd == "areg") {
      return('fixest::ssc(K.adj = TRUE, K.fixef = "full", G.adj = TRUE)')
    }
    if (is_ml) {
      return("fixest::ssc(K.adj = TRUE, G.adj = TRUE)")
      #return('fixest::ssc(adj = FALSE, cluster.adj = TRUE)')
    }
    return('fixest::ssc()')
  }

  if (is_ml) {
    return('fixest::ssc(K.adj = TRUE, G.adj = TRUE)')
  }

  return('fixest::ssc()')
}



# Ideally this is independent of the original language from
# which regvar was generated. E.g. it would be create
# if we could translate both a stata command and an R command to
# fixest
# Ideally this is independent of the original language from
# which regvar was generated. E.g. it would be create
# if we could translate both a stata command and an R command to
# fixest
# Ideally this is independent of the original language from
# which regvar was generated. E.g. it would be create
# if we could translate both a stata command and an R command to
# fixest
regvar_to_formula_fixest = function(regvar, regxvar, cmdpart, reg = NULL) {
  restore.point("regvar_to_formula_fixest")

  add_main_effects = TRUE

  rv = regvar %>% filter(role == "dep" | absorbed_fe)
  # Update: for variables starting with _I (typically generated by xi)
  # in_regcoef does not always work proper.
  # Example:   artid = "aejmac_3_3_5"; steps = 3
  # So we assume they are part of the formula
  # possibly a problem arises if they are dropped...
  # at some point I need to think on more robust handling
  rxv = regxvar %>% filter(role !="exo" | in_regcoef | startsWith(cterm,"_I"))

  rv = rv %>% mutate(
    prefix = str.left.of(cterm,"@", not.found=rep("", length(cterm))) %>% tolower()
  )

  rxv = rxv %>% mutate(
    prefix = str.left.of(cterm,"@", not.found=rep("", length(cterm))) %>% tolower()
  )

  depvars = rv$cterm[rv$role=="dep"]
  depvars = replace_cterm_special_symbols(depvars)
  form = paste0(paste0("`",depvars,"`", collapse=" + "), " ~ ")

  omit_constant = FALSE
  if (!is.null(reg) && "flags" %in% names(reg)) {
    omit_constant = stringi::stri_detect_fixed(reg$flags, "noconst")
  } else if (!is.null(cmdpart)) {
    omit_constant = any(cmdpart$part=="opt" & startsWith(tolower(cmdpart$content), "nocon"))
  }

  rhs_terms = character()
  if (omit_constant) {
    rhs_terms = c(rhs_terms, "0")
  }

  # Exogeneous x that are no FE
  rows = which(rxv$role == "exo")
  if (sum(rows)>0) {
    rhs_terms = c(rhs_terms, paste0("`",unique(rxv$cterm[rows]),"`"))
  } else {
    if (!omit_constant) {
      rhs_terms = c(rhs_terms, "1")
    }
  }

  form = paste0(form, paste0(rhs_terms, collapse= " + "))

  # Exogeneous x as FE
  rows = which(rv$role == "exo" & rv$absorbed_fe)
  if (sum(rows)>0) {
    fe_terms = rv[rows, ] %>%
      group_by(ia_cterm) %>%
      arrange(ia_pos) %>%
      summarize(
        fe_expr = {
          if (first(ia_reg_type) == "factor_numeric" && n() == 2) {
            f_idx = which(var_reg_type %in% c("factor", "fe"))[1]
            n_idx = which(!var_reg_type %in% c("factor", "fe"))[1]
            if (is.na(f_idx)) f_idx = 1
            if (is.na(n_idx)) n_idx = 2
            paste0("`", cterm[f_idx], "`[`", cterm[n_idx], "`]")
          } else {
            paste0("`", cterm, "`", collapse = "^")
          }
        }
      ) %>%
      pull(fe_expr)
    form = paste0(form, " | ", paste0(unique(fe_terms), collapse = " + "))
  }

  # Endogeneous x and instruments (never FE)
  rows = which(rxv$role == "endo")
  if (sum(rows)>0) {
    form = paste0(form, " | ",paste0("`",unique(rxv$cterm[rows]),"`", collapse= " + "))
  }
  rows = which(rxv$role == "instr")
  if (sum(rows)>0) {
    form = paste0(form, " ~ ",paste0("`",unique(rxv$cterm[rows]),"`", collapse= " + "))
  }
  form
}



# Ideally this is independent of the original language from
# which regvar was generated. E.g. it would be create
# if we could translate both a stata command and an R command to
# fixest
# Ideally this is independent of the original language from
# which regvar was generated. E.g. it would be create
# if we could translate both a stata command and an R command to
# fixest
regvar_to_formula_fixest_noregxvar = function(regvar, regxvar, cmdpart, reg = NULL) {
  restore.point("regvar_to_formula_fixest")

  add_main_effects = TRUE

  rv = regvar
  rv = rv %>% mutate(
    prefix = str.left.of(cterm,"@", not.found=rep("", length(cterm))) %>% tolower(),
    is_ia = ia_num > 1
  )

  # We replace prefix @ with .
  #rv = replace_regvar_prefix_sep(rv, "@",".")

  depvars = rv$cterm[rv$role=="dep"]
  form = paste0(paste0(depvars, collapse=" + "), " ~ ")

  omit_constant = FALSE
  if (!is.null(reg) && "flags" %in% names(reg)) {
    omit_constant = stringi::stri_detect_fixed(reg$flags, "noconst")
  } else if (!is.null(cmdpart)) {
    omit_constant = any(cmdpart$part=="opt" & startsWith(tolower(cmdpart$content), "nocon"))
  }

  rhs_terms = character()
  if (omit_constant) {
    rhs_terms = c(rhs_terms, "0")
  }

  # In stata x variables starting with o. like o.var will be omitted
  rv = rv %>% filter(prefix!="o")

  # TO DO: Specify whether in interaction A*B also A and B
  #        should be included or not.
  if (sum(rv$is_ia) >0 ) {
    ia = rv %>%
      filter(is_ia) %>%
      group_by(is_ia, ia_cterm, role, ia_num, main_pos) %>%
      arrange(desc(var_reg_type=="factor"), desc(var_reg_type=="dummy"), ia_pos) %>%
      summarize(
        absorbed_fe = first(absorbed_fe),
        ia_type = case_when(
          all(var_reg_type=="dummy") ~ "dummies",
          all(var_reg_type=="numeric") ~ "numeric",
          all(var_reg_type %in% c("dummy","factor")) ~ "factor",
          ia_num == 2 & var_reg_type[1] == "dummy" & (var_reg_type[2]=="numeric") ~ "dummy_numeric",
          ia_num == 2 & var_reg_type[1] %in% c("factor", "fe") & var_reg_type[2] == "numeric" ~ "factor_numeric",
          TRUE ~ "unknown"
        )[1],
        fe_expr = case_when(
          ia_type == "factor_numeric" ~ {
            f_idx = which(var_reg_type %in% c("factor", "fe"))[1]
            n_idx = which(!var_reg_type %in% c("factor", "fe"))[1]
            if (is.na(f_idx)) f_idx = 1
            if (is.na(n_idx)) n_idx = 2
            paste0("`", cterm[f_idx], "`[`", cterm[n_idx], "`]")
          },
          TRUE ~ paste0("`", cterm, "`", collapse="^")
        )[1],
        x_expr = paste0(
          ifelse(!var_reg_type %in% c("factor", "fe"), paste0("`", cterm, "`"), paste0("factor(`",cterm,"`)")),
          collapse= if (isTRUE(first(add_main_effects))) "*" else ":"
        )[1]
      ) %>%
      ungroup()
  } else {
    ia = NULL
  }

  no_ia = rv %>%
    filter(!is_ia) %>%
    mutate(
      fe_expr = paste0("`", cterm, "`"),
      x_expr = case_when(
        var_reg_type %in% c("factor", "fe") ~ paste0("factor(`", cterm,"`)"),
        TRUE ~ paste0("`", cterm, "`")
      )
    )

  terms = bind_rows(ia, no_ia) %>%
    arrange(main_pos)

  # Exogeneous x that are no FE
  rows = which(terms$role == "exo" & !terms$absorbed_fe)
  if (sum(rows)>0) {
    rhs_terms = c(rhs_terms, terms$x_expr[rows])
  } else {
    if (!omit_constant) {
      rhs_terms = c(rhs_terms, "1")
    }
  }

  form = paste0(form, paste0(rhs_terms, collapse= " + "))

  # Exogeneous x as FE
  rows = which(terms$role == "exo" & terms$absorbed_fe)
  if (sum(rows)>0) {
    form = paste0(form, " | ",paste0(terms$fe_expr[rows], collapse= " + "))
  }

  # Endogeneous x and instruments (never FE)
  rows = which(terms$role == "endo")
  if (sum(rows)>0) {
    form = paste0(form, " | ",paste0(terms$x_expr[rows], collapse= " + "))
  }
  rows = which(terms$role == "instr")
  if (sum(rows)>0) {
    form = paste0(form, " ~ ",paste0(terms$x_expr[rows], collapse= " + "))
  }
  form
}

stata_to_r_code_fixest_fit.old = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_fixest_fit")

  depvars = regvar$cterm[regvar$role=="dep"]
  if (length(depvars)==1) {
    ycode = paste0('y=dat["', depvars,'"]')
  } else {
    ycode = paste0('y=cbind(', paste0('dat["', depvars,'"]', collapse=","),')')
  }

}

```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_fixest.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_lm.R
```
# TO DO: VCOV
# TO DO: VCOV
stata_to_r_code_lm = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_lm")

  org_depvars = regvar$cterm[regvar$role=="dep"]
  mod_depvars = replace_cterm_special_symbols(org_depvars)

  formula = regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)

  command = "lm"
  arg_str = c(
    paste0("formula = formula"),
    paste0('data = dat')
  )

  rcmd_code = paste0('rcmd = "',command,'"')
  # We use the default ssc arguments since they are closest to the
  # Stata defaults
  if (all(org_depvars==mod_depvars)) {
    data_code = ""
  } else {
    data_code = paste0(
      'dat[["', mod_depvars,'"]] = dat[["', org_depvars,'"]]',
      collapse="\n"
    )
  }

  # Apply explicit listwise deletion to emulate Stata's e(sample)
  lw_code = r_listwise_deletion_code(regvar)
  if (nzchar(lw_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", lw_code) else lw_code
  }

  # Apply dynamic weights via centralized helper
  wt = r_weight_code(reg, template = "dat[['%s']]")
  if (nzchar(wt$data_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", wt$data_code) else wt$data_code
  }
  if (nzchar(wt$weight_arg)) {
    arg_str = c(arg_str, wt$weight_arg)
  }

  formula_code = paste0('formula = ', formula)
  reg_code = paste0('reg = ', command, "(", paste0(arg_str, collapse=","),")")

  code_df = tibble(part = c("rcmd","data","formula", "reg"), code = c(rcmd_code,data_code, formula_code, reg_code))


  use_summary=FALSE
  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=use_summary, use_conf_int=TRUE)
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}

regvar_to_formula_lm = function(regvar, regxvar, cmdpart, reg = NULL) {
  regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_lm.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_mfx.R
```
example = function() {

  dat = tibble(y=sample(0:1, size=100, replace=TRUE), x1 = rnorm(100), x2 = rnorm(100))
  reg = glm(y~x1+x2,family = binomial(link = "probit"), data=dat)

  library(mfx)
  mfx=probitmfx(y~x1+x2, data=dat)
  coeftest(mfx,vcov. = sandwich::vcovHAC(mfx))

  broom::tidy(mfx)

}


stata_to_r_code_mfx = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_mfx")

  # Ignore dropped regvars (if they are nor part of an interaction)
  #regvar = filter(regvar, !is_dropped | ia_cterm != cterm)

  # Currently we just use the fixest formula
  formula = regvar_to_formula_fixest(regvar,regxvar, cmdpart, reg = reg)

  cmd = reg$cmd
  if (cmd=="dprobit") {
    rcmd = "probitmfx"
  } else {
    stop("Cannot yet translate Stata command ", cmd)
  }

  # The exclude='select' arguments avoids overwriting
  # of dplyr's select function
  library_code = "library(MASS, exclude='select')\nlibrary(mfx)\n  "
  rcmd_code = paste0('rcmd = "',rcmd,'"')
  # We use the default ssc arguments since they are closest to the
  # Stata defaults
  formula_code = paste0('formula = ', formula)

  data_code = r_listwise_deletion_code(regvar)

  is_binary = reg$cmd %in% c("logit", "xtlogit", "probit", "xtprobit", "dprobit", "clogit", "logistic", "exlogistic")
  if (is_binary && isTRUE(opts$drop_perfect_predictors)) {
    mod_depvars = regvar$cterm[regvar$role=="dep"]
    pred_cols = unique(regxvar$cterm)
    pred_cols = setdiff(pred_cols, c("(Intercept)", ""))
    if (length(pred_cols) > 0) {
      pred_str = paste0('c(', paste0('"', pred_cols, '"', collapse=", "), ')')
      dp_code = paste0(
        'dp_cols = intersect(', pred_str, ', colnames(dat))\n',
        'dp_res = regtranslate::stata_drop_perfect_predictors(dat, "', mod_depvars[1], '", dp_cols, verbose = TRUE)\n',
        'dat = dp_res$dat'
      )
      data_code = paste0(data_code, "\n", dp_code)
    }
  }

  # mfx
  arg_str = NULL
  if (reg$se_category == "robust") {
    arg_str = "robust = true"
  } else if (reg$se_category == "cluster") {
    clustervar = extract_clustervar_from_se_args(reg$se_args)
    arg_str = paste0('clustervar1 = "', clustervar[1],'"')
    if (reg$se_type == "twoway") {
      arg_str = c(arg_str, paste0('clustervar2 = "', clustervar[2],'"'))
    }
  }
  arg_str = c(
    paste0("formula = formula"),
    paste0('data = dat'),
    arg_str
  )

  reg_code = paste0('reg = ', rcmd,'(', paste0(arg_str, collapse=","),")")
  code_df = tibble(part = c("library", "rcmd","data","formula","reg"), code = c(library_code, rcmd_code,data_code,formula_code,reg_code))
  code_df = code_df[code_df$code != "", ]

  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=FALSE, use_conf_int=TRUE)
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_mfx.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_plm.R
```
stata_to_r_code_plm = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_plm")

  org_depvars = regvar$cterm[regvar$role=="dep"]
  mod_depvars = replace_cterm_special_symbols(org_depvars)

  formula = regvar_to_formula_plm(regvar, regxvar, cmdpart, reg = reg)

  command = "plm::plm"
  arg_str = c(
    paste0("formula = formula"),
    paste0("data = dat")
  )

  rcmd_code = paste0('rcmd = "',command,'"')

  # Prepare data modifications in correct order
  data_code_parts = character(0)

  if (any(org_depvars != mod_depvars)) {
    data_code_parts = c(data_code_parts, paste0('dat[["', mod_depvars,'"]] = dat[["', org_depvars,'"]]', collapse="\n"))
  }

  lw_code = r_listwise_deletion_code(regvar)
  if (nzchar(lw_code)) data_code_parts = c(data_code_parts, lw_code)

  wt = r_weight_code(reg, template = "dat[['%s']]")
  if (nzchar(wt$data_code)) data_code_parts = c(data_code_parts, wt$data_code)
  if (nzchar(wt$weight_arg)) arg_str = c(arg_str, wt$weight_arg)

  # Duplicate index variables for plm so they don't get cast to factors if used as regressors
  panelvar = reg$panelvar[1]
  timevar = reg$timevar[1]
  if (!is.na(panelvar) && nzchar(panelvar)) {
    data_code_parts = c(data_code_parts, paste0("dat[['.plm.id']] = dat[['", panelvar, "']]"))
    if (!is.na(timevar) && nzchar(timevar)) {
      data_code_parts = c(data_code_parts, paste0("dat[['.plm.time']] = dat[['", timevar, "']]"))
      arg_str = c(arg_str, "index = c('.plm.id', '.plm.time')")
    } else {
      arg_str = c(arg_str, "index = '.plm.id'")
    }
  }

  # Model type
  flags = if (!is.null(reg$flags) && !is.na(reg$flags)) strsplit(reg$flags, ",\\s*")[[1]] else character(0)
  if ("re" %in% flags) {
    arg_str = c(arg_str, "model = 'random'")
  } else if ("fe" %in% flags) {
    arg_str = c(arg_str, "model = 'within'")
  } else if ("be" %in% flags) {
    arg_str = c(arg_str, "model = 'between'")
  } else if ("fd" %in% flags) {
    arg_str = c(arg_str, "model = 'fd'")
  }

  # Rename columns to avoid plm choking on `#` and `=`
  data_code_parts = c(data_code_parts, "dat = regtranslate::cterm_to_saveterm_cols(dat)")

  data_code = paste0(data_code_parts, collapse = "\n")

  formula_code = paste0('formula = ', formula)
  reg_code = paste0('reg = ', command, "(", paste0(arg_str, collapse=","),")")

  library_code = "# Don't call library(plm), would overload dplyr::lag"

  code_df = tibble(part = c("library", "rcmd","data","formula", "reg"), code = c(library_code, rcmd_code,data_code, formula_code, reg_code))

  sum_code = "sum = summary(reg)"

  # Handle VCOV for robust/cluster
  vcov_type = fixest_vcov_type_from_regdb(reg$se_type, reg$se_args)
  if (vcov_type %in% c("cluster", "twoway", "multiway")) {
    clustervar = extract_clustervar_from_se_args(reg$se_args)
    if (length(clustervar) > 0) {
      if (clustervar[1] == panelvar) {
        # plm default for cluster="group" is robust to panel correlation
        sum_code = "sum = lmtest::coeftest(reg, vcov = plm::vcovHC(reg, type = 'HC1', cluster = 'group'))"
        #library_code = paste0(library_code, "\nlibrary(lmtest)")
        code_df$code[1] = library_code
      } else {
        # Fallback to vcovHC for group if it's single cluster
        sum_code = paste0("sum = lmtest::coeftest(reg, vcov = plm::vcovHC(reg, type = 'HC1', cluster = 'group'))")
        #library_code = paste0(library_code, "\nlibrary(lmtest)")
        code_df$code[1] = library_code
      }
    }
  } else if (vcov_type == "hetero") {
     sum_code = "sum = lmtest::coeftest(reg, vcov = plm::vcovHC(reg, type = 'HC1', cluster = 'time'))"
     #library_code = paste0(library_code, "\nlibrary(lmtest)")
     code_df$code[1] = library_code
  }

  code_df = bind_rows(
    code_df,
    tibble(part = c("sum"), code = c(sum_code))
  )

  if (opts$add_broom) {
    use_summary_for_tidy = grepl("coeftest", sum_code)
    code_df = add_reg_broom_code(code_df, use_summary=use_summary_for_tidy, use_conf_int=TRUE)

    # broom::glance doesn't work well on coeftest. If sum is coeftest, we run glance on reg instead.
    glance_idx = which(code_df$part == "glance")
    if (length(glance_idx) > 0) {
      code_df$code[glance_idx] = "glance = broom::glance(reg)"
    }

    # Restore original cterms for broom::tidy output
    code_df = bind_rows(
      code_df,
      tibble(part = "ct_fix", code = "ct$term = regtranslate::saveterm_to_cterm(ct$term)")
    )
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}

regvar_to_formula_plm = function(regvar, regxvar, cmdpart, reg = NULL) {
  restore.point("regvar_to_formula_plm")

  rv = regvar %>% filter(role == "dep" | absorbed_fe)
  rxv = regxvar %>% filter(role !="exo" | in_regcoef | startsWith(cterm,"_I"))

  depvars = rv$cterm[rv$role=="dep"]
  depvars = cterm_to_saveterm(depvars)
  form = paste0(paste0("`",depvars,"`", collapse=" + "), " ~ ")

  omit_constant = FALSE
  if (!is.null(reg) && "flags" %in% names(reg)) {
    omit_constant = stringi::stri_detect_fixed(reg$flags, "noconst")
  } else if (!is.null(cmdpart)) {
    omit_constant = any(cmdpart$part=="opt" & startsWith(tolower(cmdpart$content), "nocon"))
  }

  rhs_terms = character()
  if (omit_constant) {
    rhs_terms = c(rhs_terms, "0")
  }

  rows = which(rxv$role == "exo")
  if (sum(rows)>0) {
    rhs_terms = c(rhs_terms, paste0("`", cterm_to_saveterm(unique(rxv$cterm[rows])), "`"))
  } else {
    if (!omit_constant) {
      rhs_terms = c(rhs_terms, "1")
    }
  }

  endo_rows = which(rxv$role == "endo")
  if (sum(endo_rows)>0) {
    rhs_terms = c(rhs_terms, paste0("`", cterm_to_saveterm(unique(rxv$cterm[endo_rows])), "`"))
  }

  form = paste0(form, paste0(rhs_terms, collapse= " + "))

  # IVs
  instr_rows = which(rxv$role == "instr")
  if (sum(instr_rows)>0) {
    iv_terms = character()
    if (omit_constant) iv_terms = c(iv_terms, "0")
    if (sum(rows)>0) iv_terms = c(iv_terms, paste0("`", cterm_to_saveterm(unique(rxv$cterm[rows])), "`"))
    iv_terms = c(iv_terms, paste0("`", cterm_to_saveterm(unique(rxv$cterm[instr_rows])), "`"))
    form = paste0(form, " | ", paste0(iv_terms, collapse= " + "))
  }

  form
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_plm.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_quantreg.R
```

stata_to_r_code_quantreg = function(reg, regvar,regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_quantreg")

  # Ignore dropped regvars (if they are nor part of an interaction)
  #regvar = filter(regvar, !is_dropped | ia_cterm != cterm)


  # Currently we just use the fixest formula
  formula = regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)

  rcmd = "rq"

  library_code = paste0("library(quantreg)")
  rcmd_code = paste0('rcmd = "',rcmd,'"')
  # We use the default ssc arguments since they are closest to the
  # Stata defaults
  formula_code = paste0('formula = ', formula)

  arg_str = NULL
  if (reg$se_category != "iid") {
    stop("Currently stata_to_r_code_quantreg is only implemented for iid standard errors. ")
  }
  arg_str = c(
    paste0("formula = formula"),
    paste0('data = dat'),
    arg_str
  )

  data_code = r_listwise_deletion_code(regvar)

  # Apply dynamic weights via centralized helper
  wt = r_weight_code(reg, template = "dat[['%s']]")
  if (nzchar(wt$data_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", wt$data_code) else wt$data_code
  }
  if (nzchar(wt$weight_arg)) {
    arg_str = c(arg_str, wt$weight_arg)
  }

  opts_df = cmdpart_to_opts_df(cmdpart)
  opt_row = which(opts_df$opt=="quantile")
  if (length(opt_row)>0) {
    arg_str = c(arg_str, paste0("tau = ", opts_df$opt_arg[opt_row]))
  }


  reg_code = paste0('reg = suppressWarnings(', rcmd,'(', paste0(arg_str, collapse=","),"))")

  code_df = tibble(part = c("library", "rcmd","data","formula","reg"), code = c(library_code, rcmd_code,data_code,formula_code,reg_code))
  code_df = code_df[code_df$code != "", ]

  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=FALSE, use_conf_int=TRUE)
    code_df = bind_rows(code_df, tibble(part="ct_mod",code='
ct = mutate(ct, std.error=NA_real_, statistic= NA_real_,  p.value = NA_real_)
if ("logLik" %in% names(glance)) {
  glance$logLik = as.numeric(glance$logLik)
}
'))
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}

tidy.tobit <- function(x, ...) {
  class(x) <- "survreg"
  tidy(x, ...)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_quantreg.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r.R
```
# Translate to R code
example = function() {
  project.dir = "C:/libraries/repbox/projects_reg/testsupp"

  core = readRDS(file.path(project.dir, "regdb","reg_core.Rds"))
  regs = core$reg
  varinfo = readRDS(file.path(project.dir, "regdb","base_varinfo.Rds"))
  regvars =  varinfo$regvar

  step = 3
  reg = regs[regs$step==step,]
  regvar = regvars[regvars$step==step,]

  code_df = reg_stata_to_r_code(reg, regvar, opts = code_options(add_function=TRUE, add_restorepoint = TRUE))
}


code_options = function(prefer_sandwich=FALSE, prefer_summary=FALSE, add_broom=TRUE, add_function=FALSE, add_restorepoint=FALSE, drop_perfect_predictors=TRUE, match_stata_singletons=TRUE) {
  list(
    prefer_sandwich = prefer_sandwich,
    prefer_summary = prefer_summary,
    add_broom = add_broom,
    add_function = add_function,
    add_restorepoint = add_restorepoint,
    drop_perfect_predictors = drop_perfect_predictors,
    match_stata_singletons = match_stata_singletons
  )
}

reg_stata_to_r_code = function(reg, regvar, regxvar, cmdpart, prefer="fixest", opts=code_options()) {
  restore.point("reg_stata_to_r_code")

  r_cmd = get_stata_to_r_cmd(reg$cmd, prefer, reg = reg)
  if (isTRUE(r_cmd == "no_trans") | is.na(r_cmd)) {
    cat(paste0("The Stata command ", reg$cmd, " is not yet implemented for translation in regtranslate."))
    return(NULL)
  }

  args = list(reg=reg, regvar=regvar,regxvar, cmdpart=cmdpart, opts=opts)
  fun = paste0("stata_to_r_code_",r_cmd)
  res = do.call(fun, args)

  # Centralized injection of Date to numeric conversion code
  if (!is.null(res) && "data" %in% res$part) {
    date_code = r_date_to_numeric_code(regvar, runid = reg$runid)
    if (nzchar(date_code)) {
      data_idx = which(res$part == "data")[1]
      if (nzchar(res$code[data_idx])) {
        res$code[data_idx] = paste0(date_code, "\n", res$code[data_idx])
      } else {
        res$code[data_idx] = date_code
      }
    }
  }

  res
}

reg_stata_to_r_formula = function(reg, regvar, regxvar, cmdpart, prefer="fixest", opts=code_options()) {
  restore.point("reg_stata_to_r_formula")

  r_cmd = get_stata_to_r_cmd(reg$cmd, prefer, reg = reg)
  if (isTRUE(r_cmd == "no_trans")) {
    return(NULL)
  } else if (is.na(r_cmd)) {
    stop(paste0("The Stata command ", reg$cmd, " is neither implemented for translation nor specified in stata_cmds_without_r_translation()"))
  }

  args = list(regvar=regvar,regxvar=regxvar, cmdpart=cmdpart, reg=reg)
  fun = paste0("regvar_to_formula_",r_cmd)
  res = do.call(fun, args)
  as.formula(res)
}

get_stata_to_r_cmd = function(cmd, prefer = NULL, reg = NULL) {
  restore.point("get_stata_to_r_cmd")
  df = stata_to_r_cmds_df()
  rows = df$stata_cmd == cmd
  if (length(rows)==0) return(NA)
  r_cmds = df$r_cmd[rows]

  if (!is.null(reg) && cmd %in% c("xtreg", "xtivreg")) {
    flags = if (!is.null(reg$flags) && !is.na(reg$flags)) strsplit(reg$flags, ",\\s*")[[1]] else character(0)
    if ("re" %in% flags || "be" %in% flags || "mle" %in% flags || "pa" %in% flags || "fd" %in% flags) {
      if ("plm" %in% r_cmds) return("plm")
      return("plm")
    }
  }

  if (length(rows)==1 | length(prefer)==0) return(r_cmds[1])
  ma = match(r_cmds, prefer)
  best = which.min(ma)
  if (length(best)==0) return(r_cmds[1])
  r_cmds[best[1]]
}


stata_to_r_cmds_df = function(cmd) {
  li = list(
    # If you add commands here make to sure that you update the to_r_fixest.R code
    fixest.. = c("regress","reg", "cgmreg", "ivregress","ivreg","ivreg2","xtivreg", "xtivreg2", "reghdfe","ivreghdfe", "xtreg","areg","ppmlhdfe","logit","xtlogit","probit","xtprobit","dprobit", "newey", "nbreg", "gnbreg", "poisson", "xtpoisson", "clogit"),
    plm.. = c("xtreg", "xtivreg"),
    lm.. = c("regress","reg", "newey"),
    ivreg.. = c("ivregress","ivreg","ivreg2", "xtivreg", "xtivreg2"),
    quantreg.. = c("qreg"),
    # Note that parmest does return coefficients not marginal
    # effects for dprobit. So we don't use mfx
    #mfx... = c("dprobit"),
    tobit.. = c("tobit"),
    stcox.. = c("stcox")
  )
  stata_cmd = unlist(li)
  r_cmd = str.left.of(names(stata_cmd),"..")
  data.frame(stata_cmd=stata_cmd,r_cmd=r_cmd,row.names = NULL)
}

add_reg_function_code = function(code_df,add_results=TRUE, add_restore_point=isTRUE(opts$add_restore_point), opts=NULL) {
  restore.point("add_reg_function_code")
  fun_header = paste0("function(dat,...){")
  rp_code = paste0('restore.point("regfun_',sample.int(1e10,1),'")')

  if (add_results) {
    results = paste0("results = list(reg=reg")
    if ("rcmd" %in% code_df$part) {
      results = paste0(results, ",rcmd=rcmd")
    }

    if ("sum" %in% code_df$part) {
      results = paste0(results, ",sum=sum")
    }
    if ("tidy" %in% code_df$part) {
      results = paste0(results, ",ct=ct")
    }
    if ("glance" %in% code_df$part) {
      results = paste0(results, ",glance=glance")
    }
    results = paste0(results,")")
    results_df = tibble(part="results", code=results)
  } else {
    results_df = NULL
  }
  fun_footer = paste0("return(results)\n}")

  if (add_restore_point) {
    rp_code = paste0('restore.point("regfun_',sample.int(1e10,1),'")')
    head_df = tibble(part=c("fun_header","restorepoint"),code = c(fun_header, rp_code))
  } else {
    head_df = tibble(part=c("fun_header"), code = c(fun_header))
  }
  foot_df = tibble(part=c("fun_footer"), code = c(fun_footer))

  bind_rows(
    head_df,
    code_df,
    results_df,
    foot_df
  )
}

add_reg_broom_code = function(code_df, use_summary=any(code_df$part=="sum"), use_conf_int=TRUE) {
  broom_x = if (use_summary) "sum" else "reg"
  tidy_code = paste0('ct = broom::tidy(',broom_x,",conf.int=TRUE)")
  glance_code = paste0('glance = broom::glance(',broom_x,')')

  tidy_df = tibble(
    part = c("tidy","glance"),
    code = c(tidy_code, glance_code)
  )
  bind_rows(code_df, tidy_df)
}

# update: don't quote one-sided formulas
quote_arg = function(arg) {
  quote = suppressWarnings(!has.substr(arg,"(") & !startsWith(trimws(arg), "~") & is.na(as.numeric(arg)) & is.na(as.logical(arg)))
  ifelse(quote, paste0('"', arg,'"'), arg)
}

# quote_arg = function(arg) {
#   quote = suppressWarnings(!has.substr(arg,"(") & is.na(as.numeric(arg)) & is.na(as.logical(arg)))
#   ifelse(quote, paste0('"', arg,'"'), arg)
# }

replace_regvar_prefix_sep = function(regvar, from="@", to=".") {
  regvar$cterm = gsub(from, to, regvar$cterm, fixed=TRUE)
  regvar$ia_cterm = gsub(from, to, regvar$ia_cterm, fixed=TRUE)
  regvar
}


extract_clustervar_from_se_args = function(se_args) {
  args = regdb_parse_se_args(se_args)
  clustervar = args[startsWith(names(args),"cluster")]
  clustervar
}

#' Generate R code to emulate Stata's listwise deletion (e(sample))
#'
#' Stata drops missing values for all variables in the original varlist
#' *before* omitting collinear terms. Since our R translation explicitly
#' drops collinear terms from the formula, we need to manually drop NAs
#' across all original variables to match Stata's e(sample).
r_listwise_deletion_code = function(regvar) {
  all_base_cterms = unique(regvar$cterm)
  all_base_cterms = setdiff(all_base_cterms, c("(Intercept)", ""))

  if (length(all_base_cterms) == 0) return("")

  paste0(
    "cc_cols = c(", paste0('"', all_base_cterms, '"', collapse=", "), ")\n",
    "dat = stata_drop_missing(dat, cc_cols)"
  )
}



#' Generate R code to convert Date/Datetime variables to numeric
#'
#' Fixest and other packages complain if Date variables are used directly as numeric variables.
#' We also emit a repbox_problem since effect sizes of Dates are hard to interpret.
r_date_to_numeric_code = function(regvar, runid = NULL) {
  restore.point("r_date_to_numeric_code")
  if (!"var_org_type" %in% colnames(regvar)) return("")

  rows = which(regvar$var_org_type  %in% c("Date", "POSIXct", "POSIXt", "difftime") & regvar$var_reg_type == "numeric")

  if (length(rows)==0) return("")


  date_vars = unique(regvar$cterm[rows])
  date_vars = setdiff(date_vars, c("(Intercept)", "", NA))

  if (!is.null(runid)) {
    msg = paste0("Regression uses Date/Datetime variables as numeric: ", paste(date_vars, collapse=", "), ". Effect sizes might be hard to interpret.")
    repboxUtils::repbox_problem(msg, type = "date_as_numeric", runid = runid, fail_action = "msg")
  }

  paste0(
    'dat = stata_datetime_cols_to_numeric(dat, c(', paste0('"', date_vars, '"', collapse=", "), '))'
  )
}
stata_datetime_cols_to_numeric = function(data, cols = NULL) {
  stata_date_offset_days = as.numeric(as.Date("1970-01-01") - as.Date("1960-01-01"))
  stata_datetime_offset_ms = stata_date_offset_days * 24 * 60 * 60 * 1000

  if (is.null(cols)) {
    is_dt = vapply(data, function(v) {
      inherits(v, "Date") || inherits(v, "POSIXct")
    }, logical(1))
    cols = names(data)[is_dt]
  }

  if (length(cols) == 0) return(data)

  for (col in cols) {
    v = data[[col]]

    if (inherits(v, "Date")) {
      data[[col]] = as.numeric(v) + stata_date_offset_days
    } else if (inherits(v, "POSIXct")) {
      data[[col]] = as.numeric(v) * 1000 + stata_datetime_offset_ms
    } else {
      warning(sprintf("Column '%s' is not Date or POSIXct; leaving unchanged.", col))
    }
  }

  data
}

```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_stcox.R
```
stata_to_r_code_stcox = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_stcox")

  timevar = reg$timevar[1]
  failvar = reg$panelvar[1]

  if (is.na(timevar) || !nzchar(timevar)) {
    stop("Cannot translate stcox: timevar missing (stset not found or not parsed)")
  }

  if (!is.na(failvar) && nzchar(failvar)) {
    surv_expr = paste0("survival::Surv(`", timevar, "`, `", failvar, "`)")
  } else {
    surv_expr = paste0("survival::Surv(`", timevar, "`)")
  }

  # stcox doesn't have a LHS variable in varlist. cmdparts_of_stata_reg treats the first one as dep.
  # We convert it to exo to prevent it from going to LHS.
  regvar$role[regvar$role == "dep"] = "exo"
  if (!is.null(regxvar) && nrow(regxvar) > 0) {
    regxvar$role[regxvar$role == "dep"] = "exo"
  }

  formula_rhs = regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)
  formula = paste0(surv_expr, formula_rhs)

  library_code = "library(survival)"
  rcmd_code = 'rcmd = "coxph"'

  arg_str = c(
    "formula = formula",
    "data = dat",
    'ties = "breslow"'
  )

  # Handle se
  if (reg$se_category == "robust") {
    arg_str = c(arg_str, "robust = TRUE")
  } else if (reg$se_category == "cluster") {
    clustervar = extract_clustervar_from_se_args(reg$se_args)
    if (length(clustervar) > 0) {
      arg_str = c(arg_str, paste0('cluster = dat[["', clustervar[1], '"]]'))
    }
  }

  data_code = r_listwise_deletion_code(regvar)

  # Apply dynamic weights via centralized helper
  wt = r_weight_code(reg, template = "dat[['%s']]")
  if (nzchar(wt$data_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", wt$data_code) else wt$data_code
  }
  if (nzchar(wt$weight_arg)) {
    arg_str = c(arg_str, wt$weight_arg)
  }

  formula_code = paste0('formula = ', formula)
  reg_code = paste0('reg = coxph(', paste0(arg_str, collapse=","),')')

  code_df = tibble(part = c("library", "rcmd","data","formula","reg"), code = c(library_code, rcmd_code, data_code, formula_code, reg_code))

  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=FALSE, use_conf_int=TRUE)
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_stcox.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/to_r_tobit.R
```

stata_to_r_code_tobit = function(reg, regvar, regxvar, cmdpart, opts=code_options(), parts = list()) {
  restore.point("stata_to_r_code_tobit")

  # Ignore dropped regvars (if they are nor part of an interaction)
  #regvar = filter(regvar, !is_dropped | ia_cterm != cterm)

  # Currently we just use the fixest formula
  formula = regvar_to_formula_fixest(regvar, regxvar, cmdpart, reg = reg)

  rcmd = "tobit"

  library_code = paste0("library(AER)")
  rcmd_code = paste0('rcmd = "',rcmd,'"')
  # We use the default ssc arguments since they are closest to the
  # Stata defaults
  formula_code = paste0('formula = ', formula)

  arg_str = NULL
  if (reg$se_category == "robust") {
    arg_str = c(arg_str, "robust = TRUE")
  } else if (reg$se_category == "cluster") {
    clustervar = extract_clustervar_from_se_args(reg$se_args)
    if (length(clustervar) > 0) {
      arg_str = c(arg_str, paste0('cluster = dat[["', clustervar[1],'"]]'))
    }
    if (reg$se_type %in% c("twoway", "multiway")) {
      stop("Multiway clusters not yet implemented for tobit in R")
    }
  }

  if (!is.null(cmdpart)) {
    opts_df = cmdpart_to_opts_df(cmdpart)

    # Left censoring
    ll_row = which(opts_df$opt == "ll")
    if (length(ll_row) > 0) {
      val = opts_df$opt_arg[ll_row[1]]
      if (!is.na(val) && nzchar(val)) {
        arg_str = c(arg_str, paste0("left = ", val))
      } else {
        arg_str = c(arg_str, "left = 0")
      }
    } else {
      arg_str = c(arg_str, "left = -Inf")
    }

    # Right censoring
    ul_row = which(opts_df$opt == "ul")
    if (length(ul_row) > 0) {
      val = opts_df$opt_arg[ul_row[1]]
      if (!is.na(val) && nzchar(val)) {
        arg_str = c(arg_str, paste0("right = ", val))
      } else {
        arg_str = c(arg_str, "right = 0")
      }
    }
  } else {
    arg_str = c(arg_str, "left = -Inf")
  }

  arg_str = c(
    paste0("formula = formula"),
    paste0('data = dat'),
    arg_str
  )

  data_code = r_listwise_deletion_code(regvar)

  # Apply dynamic weights via centralized helper
  wt = r_weight_code(reg, template = "dat[['%s']]")
  if (nzchar(wt$data_code)) {
    data_code = if (nzchar(data_code)) paste0(data_code, "\n", wt$data_code) else wt$data_code
  }
  if (nzchar(wt$weight_arg)) {
    arg_str = c(arg_str, wt$weight_arg)
  }

  reg_code = paste0('reg = ', rcmd,'(', paste0(arg_str, collapse=","),")\nclass(reg) = 'survreg'")

  code_df = tibble(part = c("library", "rcmd","data","formula","reg"), code = c(library_code, rcmd_code,data_code,formula_code,reg_code))
  code_df = code_df[code_df$code != "", ]

  if (opts$add_broom) {
    code_df = add_reg_broom_code(code_df, use_summary=FALSE, use_conf_int=TRUE)
  }
  if (opts$add_function) {
    code_df = add_reg_function_code(code_df)
  }
  code_df
}

tidy.tobit <- function(x, ...) {
  class(x) <- "survreg"
  tidy(x, ...)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/to_r_tobit.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/regtranslate/R/weights.R
```
#' Translate regression weight configurations into R syntax.
#'
#' Evaluates the `weights` and `flags` fields from a `reg` parcel and
#' constructs two snippets of code:
#' 1. `data_code`: A string setting up `.weight` if the weight is a mathematical expression.
#' 2. `weight_arg`: The exact string to inject into the `weights = ...` argument of the regression call.
#'
#' @param reg The single-row dataframe of the regression metadata parcel.
#' @param template A format string denoting how the final weight should be injected.
#'                 Use `"~ %s"` for fixest/formulas, or `"dat[['%s']]"` for lm/rq/tobit vectors.
#'
#' @return A list with `$data_code` and `$weight_arg`
r_weight_code = function(reg, template = "~ %s") {
  res = list(data_code = "", weight_arg = "")

  if (!"weights" %in% names(reg)) return(res)

  w_str = reg$weights
  if (is.na(w_str) || !nzchar(w_str)) return(res)

  flags = if (!is.null(reg$flags) && !is.na(reg$flags)) {
    strsplit(reg$flags, ",\\s*")[[1]]
  } else {
    character(0)
  }

  if ("weights_non_parseable" %in% flags) {
    res$weight_arg = "# Weights skipped: non-parseable expression"
    return(res)
  }

  if ("weights_expr" %in% flags) {
    res$data_code = paste0("dat[['.weight']] = with(dat, ", w_str, ")")
    res$weight_arg = paste0("weights = ", sprintf(template, ".weight"))
  } else {
    res$weight_arg = paste0("weights = ", sprintf(template, w_str))
  }

  return(res)
}
```
# END OF FILE: /home/rstudio/repbox/regtranslate/R/weights.R

-----------------------------------------------------------



# Format of proposed changes to code  files

When you suggest changes to code or text files or completely new files, you MUST use the following format for each modification. Each change must be enclosed in a `!MODIFICATION` block.

## Overall Structure

Each modification block has three parts:
1.  Start and end markers: `!MODIFICATION {{what}}` and `!END_MODIFICATION {{what}}`, where {{what}} is just a short reference to what is modified, file name or function name with with file. It will not be parsed but makes it easier for a human to understand blocks.
2.  A metadata block in **TOML format**. This block ends with a `---` separator line.
3.  A code payload block, which is a standard markdown code fence.

```
!MODIFICATION {{what}}
# TOML metadata goes here
# ...
---
```language
# New code payload goes here
```
!END_MODIFICATION {{what}}
```

We have two possible scopes for modification:
  - file (replaces complete file) or
  - function (replaces an R function).

### **Scope 1: `file`**

Use this format to create a new file or to completely rewrite an existing one.

**Required Fields:**
*   `scope = "file"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `description` (string): A brief explanation of the change in quotes ""

### **Example 1.1: Creating or modifying a file**
!MODIFICATION new_helpers.R
scope = "file"
file = "/home/rstudio/myproject/R/new_helpers.R"
description = "Create a new file for helper functions."
---
```r
# A new helper function
say_hello = function(name) {
  paste0("Hello, ", name)
}
```
!END_MODIFICATION new_helpers.R


## **Scope 2: `function`**

Use this fomrat to replace an existing function or to insert a new function. The new code payload should contain the complete function, including any preceding comments.

### **Fields for replacing an existing function:**
*   `scope = "function"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `function_name` (string): The name of the function to be replaced.
*   `description` (string): A brief explanation of the change in quotes.

### **Fields for inserting a new function:**
*   `scope = "function"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `description` (string): A brief explanation of the change, enclose in quotes.
*   **One of** the following fields to specify the insertion point. They are mutually exclusive.
    *   `insert_top = true`: Insert at the top of the file.
    *   `insert_bottom = true`: Insert at the bottom of the file.
    *   `insert_before_fun = "function_name"`: Insert before the specified function.
    *   `insert_after_fun = "function_name"`: Insert after the specified function.


### **Example 2.1: Replacing an existing function**
!MODIFICATION calculate_sum utils.R
scope = "function"
file = "R/utils.R"
function_name = "calculate_sum"
description = "Update `calculate_sum` to handle NA values correctly.""
---
```r
#' Calculate the sum of a vector, ignoring NAs
calculate_sum = function(vec) {
  sum(vec, na.rm = TRUE)
}
```
!END_MODIFICATION calculate_sum utils.R

### **Example 2.2: Inserting a new function at the bottom of a file (here was an absolute file path given)**
!MODIFICATION is_positive in R/utils.R
scope = "function"
file = "/home/myuser/mypkg/R/utils.R"
insert_bottom = true
description = "Add a new helper function to check for positivity."
---
```r

#' Check if a number is positive
is_positive = function(n) {
  n > 0
}
```
!END_MODIFICATION is_positive in R/utils.R

### **Example 2.3: Inserting a new function after a specific function**
!MODIFICATION is_negative in R/utils.R
scope = "function"
file = "R/utils.R"
insert_after_fun = "is_positive"
description = "Add a new helper function `is_negative` after `is_positive`."
---
```r

#' Check if a number is negative
is_negative = function(n) {
  n < 0
}
```

Important if the file is shown with absolute path in the file contents above also
use the absolute path in the file = argument in your modification header.



##################################
# Your Task
##################################

Do we already have support for the Stata command newewy? Can we also add support for newey2

